### ISSUE TITLE
Replace `serial` primary keys with something that won't run out

### ISSUE THREAD

**Issue by leodasvacas** [graphprotocol/graph-node#1034]
We currently `serial` at least for `large_notifications`. We haven't even reached a million of those yet on the hosted service, but we will eventually run out of serial primary keys. As an alternative we should use `bigserial`, `UUID` or if we upgrade postgres the new `IDENTITY` columns.

**Comment by lutter** [comment]
I don't think this is actually an issue: we are at ~ 500M in the `large_notifications.id` column, which means that there is room for about 4000 times as many large notifications before we hit the top of the range of an `int`; with current usage, that would take about 2000 years.

We could change the sequence to [cycle around](https://www.postgresql.org/docs/9.6/sql-altersequence.html) to guard against the unlikely case that we'll ever hit a wraparound, since we only ever use a tiny part of the possible space of `ids` at any given time.

**Comment by leodasvacas** [comment]
Thanks for doing more careful math, seems like this is a non-issue.
