### ISSUE TITLE
Make entity notifications robust

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#1043]

**Comment by leodasvacas** [comment]
@olibearo, @fordN and me met to discuss what sort of measures can be taken here, at different time frames. Pinging @lutter since this is db-related.

In the short-term, the question is how should the graph-node respond if it detects that notifications may have been missed, be it due to the timed cleanup or an error connecting to the db. Here we came up with two ideas:

1. The node should crash. It would then be restarted and query the db source of truth again. This works ok for internal subscriptions (such as subgraph assignments), but for user subscriptions we're relying on the graphql client re-establishing the connection.

2. The node has a redundant polling system, that's less responsive but picks up what might be missed by notifications. This is would be a robust way to deal with the timed cleanup case, but is probably more code complexity than crashing, and is a performance cost when everything is going ok.

I proposed 1 and @olibearo proposed 2. @fordN feels the possibility of still missing a notification with the larger timeout is very unlikely. it'd be good to get more opinions here.

A mid-term goal: Switch to an tokio-postgres so we handle notifications in an async way. Tracked in #1053.

A Long-term solution is to split up the firehose of notifications, we'd have more fine-grained postgres channels, instead of a single channel for everything, and keep something like a `(channel_id, subcription_topic, time_to_live)` tuple in the DB. These would be created by subscriptions, and indexing nodes would query which channels they should send the updates to.

The even longer term question is what concept of subscriptions will exist in the hybrid network and its read interface, and how that will be supported. It will likely build on the lower-level parts of our existing subscription system, so it seems worth maintaining that even if its future is uncertain.

**Comment by lutter** [comment]
Looking at this in some more detail, the only time we can possibly miss notifications is when they have to spill into the `large_notifications` table, i.e. when the message itself is pretty big (~ 7kB) This only happens if a subgraph touches a lot of entities in one block and is relatively rare, and missing notifications will manifest as GraphQL subscriptions not updating when they should have.

The bigger problem we had was that a missed large notification would panic the notification listener, which would then result in a node missing all subsequent notifications, small and large. To me, the way to make this more robust is
* make sure the notification listener can never panic (I'll post a PR for that in a minute)
* to mitigate missing large notifications, we could include more information in the message that is sent when a large notification is pending and somehow use that to force a possibly unneeded subscription update. Right now, we only send the id of the entry in `large_notifications`, and if that goes missing before we use it, we know nothing about the notification. But there is a lot of room in the pg message itself for more info, at least the subgraph that is affected by the message

**Comment by Jannis** [comment]
Large notifications don't seem to be rare; in fact most deployments represent a large notification, and deployments the things we'd best not miss. Having said that, not panicking is an improvement. And with the larger cleanup interval, we haven't seen the issue again.

@lutter Would you say the changes we made are good enough to close this?

**Comment by leodasvacas** [comment]
I agree that missing a notification is a hypothetical issue with the increased interval and not panicking will make it easier to catch. But still this is issue, even if low priority, imo it's good to keep this open to track the ideas we had for improvements.

**Comment by lutter** [comment]
> Large notifications don't seem to be rare; in fact most deployments represent a large notification, and deployments the things we'd best not miss.

I am a little surprised by that. What are we sending for deployment (IIRC the assignment event) that makes the notification larger than 7kB or so?

> @lutter Would you say the changes we made are good enough to close this?

I think so, yes.

**Comment by Jannis** [comment]
> > Large notifications don't seem to be rare; in fact most deployments represent a large notification, and deployments the things we'd best not miss.
> I am a little surprised by that. What are we sending for deployment (IIRC the assignment event) that makes the notification larger than 7kB or so?

All the subgraph meta data entities (version, deployment, manifest, data sources etc.).
