### ISSUE TITLE
Crashing upon upgrade to v0.16.1

### ISSUE THREAD

**Issue by iameli** [graphprotocol/graph-node#1363]
Jumping between meetings so this'll be a quick report, but @adamsoffer and I just tried to upgrade Livepeer's graph-nodes from v0.15.1 to v0.16.1 and it's now repeatedly crashing. [Logs are here](https://gist.github.com/iameli/1e2a626e832eb13e94853581a8591db3), can add more detail later.

Pertinent line seems to be `thread 'tokio-runtime-worker-3' panicked at 'assertion failed: block_ptr_from.number < block_ptr_to.number', store/postgres/src/store.rs:852:21`

**Comment by leoyvens** [comment]
@iameli That is known to happen if you have two graph nodes indexing the same subgraph. All it takes for that to happen is to have two graph nodes connected to the same db. To correctly have more than one graph node connected to the same db, pass in the `--node-id` argument in the CLI or use the `GRAPH_NODE_ID` env var, so that they have different node ids. If you don't want to lose your current syncing progress, keep the default node id on one of the nodes and configure different node ids on the others.

**Comment by leoyvens** [comment]
@iameli no, that's orthogonal, but you do want to have a single node with `DISABLE_BLOCK_INGESTOR=true`, preferrably one that you set to a node id different from the default, so that it's not syncing any subgraphs.

**Comment by iameli** [comment]
Got it, thanks! I had all our nodes with separate `--node-id` and it once again seems to be working. Thanks for the quick response! Will reopen this if I run into any other issues.
