### ISSUE TITLE
GraphQL queries for interfaces return the same entity multiple times

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#1438]
The following query against [protofire/roken-registry](https://thegraph.com/explorer/subgraph/protofire/token-registry)(QmaTK1m8VszFp7iijbWrX65iN8e5zogvJYvUAck7HEvAtQ) shows the problem:

```graphql
query getTokensWithEvents {
  tokens(first: 2) {
    id
    symbol
    events(first: 5, orderBy: timestamp, orderDirection: desc) {
      __typename
      id
    }
  }
}
```

The result has 20 events for each token, rather than the 5 that were requested. The problem is in the GraphQL processing (`graphql::store::prefetch`), the underlying SQL query correctly returns 5 events for each token. The first 5 events for each token are the requested events in the correct order.

**Comment by juanmardefago** [comment]
Found a similar issue while working on [protofire/ray](https://thegraph.com/explorer/subgraph/protofire/ray).

To sum it up, on our token structure we have different events with a common interface, and we also have a query for an interface that returns the same entity multiple times, but we found out that it works as expected if we query for only one token (querying for more than one token results in this issue, and the amount of repetitions that each entity has is oddly suspicious, since it's the same amount of event implementations that the interface has)

Here are the queries for that subgraph that reproduce this error:

Querying for 1 token, working as expected:
```
  raytokens (first:1){
    events {
      id
      __typename
    }
  }
```

Result:
![token1](https://user-images.githubusercontent.com/17829741/73945748-90088c00-48d3-11ea-9adf-51cb5b2f6bb0.png)


Querying for 2 tokens, now the same event is repeated 4 times:
```
  raytokens (first:2){
    events {
      id
      __typename
    }
  }
```

Result:
![token2](https://user-images.githubusercontent.com/17829741/73945770-9a2a8a80-48d3-11ea-9b73-e61f58e28c87.png)

Also, it ignores the request to limit the amount of responses if we were to pass it, just as described in the original comment. Here's an example:

Querying for 2 tokens, now the same event is repeated 4 times:
```
  raytokens (first:2){
    events (first: 1) {
      id
      __typename
    }
  }
```

Result: 
![token2first1](https://user-images.githubusercontent.com/17829741/73946072-18872c80-48d4-11ea-8086-b825c1e32062.png)

**Comment by juanmardefago** [comment]
Also, I just modified the code to delete one of the interface implementing entities, and run the query again, to be 100% sure that the amount of repetitions is related to the amount of interface implementing entities, and it seems to be the case.

Here's a screenshot of the changes made on a development subgraph:
![token2delete1event](https://user-images.githubusercontent.com/17829741/73946723-238e8c80-48d5-11ea-9503-ea6c50308de4.png)
