### ISSUE TITLE
Failed to handle Ethereum event with handler "handleTransfer ... Value is not an array

### ISSUE THREAD

**Issue by wighawag** [graphprotocol/graph-node#1579]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

I am building a generic graph for EIP-712 contracts (see https://thegraph.com/explorer/subgraph/wighawag/eip721-subgraph) and got the following error

```
INFO
Done processing Ethereum event, waiting_ms: 0, total_ms: 99, handler: handleTransfer, signature: Transfer(indexed address,indexed address,indexed uint256), block_hash: 0x83735b6348fcfb242572e0f2d63c063af73e6bb6694b37e2f532d7ab007d7fb9, block_number: 5806610

ERROR
Subgraph instance failed to run: Failed to process trigger in block #5806610 (83735b6348fcfb242572e0f2d63c063af73e6bb6694b37e2f532d7ab007d7fb9), transaction 52e3fc9957c70126ead9c31c97f58059c9e1e402deb29039cd4ea4be02bf83fa: Failed to handle Ethereum event with handler "handleTransfer": Mapping aborted at ~lib/@graphprotocol/graph-ts/index.ts, line 1046, column 4, with message: Value is not an array., code: SubgraphSyncingFailure, id: QmYSFfVAjhGJkrG7wrXuYUZyLtdAK5oeGX43cVNSHmpoVE


INFO
contract : 0x7b70405fba653cc8eff5afad1c5079d7da0a0247, data_source: EIP721, block_hash: 0x83735b6348fcfb242572e0f2d63c063af73e6bb6694b37e2f532d7ab007d7fb9, block_number: 5806610

INFO
Skipping handler because the event parameters do not match the event signature. This is typically the case when parameters are indexed in the event but not in the signature or the other way around, error: Invalid data, event: Transfer(indexed address,indexed address,indexed uint256), handler: handleTransfer, block_hash: 0x83735b6348fcfb242572e0f2d63c063af73e6bb6694b37e2f532d7ab007d7fb9, block_number: 5806610

WARNING
No matching handlers found for event with topic0 `ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef`, data_source: EIP721, block_hash: 0x83735b6348fcfb242572e0f2d63c063af73e6bb6694b37e2f532d7ab007d7fb9, block_number: 5806610
```

In my subgraph.yml

I have the following for Transfer events :

```
 eventHandlers:
        - event: Transfer(indexed address,indexed address,indexed uint256)
          handler: handleTransfer
```

The contract that trigger the error have different indexed paramater. it does not have the tokenId indexed, but that should not break the graph

**Comment by fordN** [comment]
I believe the issue is with the way `contractInfo.tokens` is being updated.  

Due to the type conversions made behind the scenes of the generated entity classes, accessing arrays creates a copy instead of returning a reference.
In the mappings an Entity is just a map of string to Value, where Value can hold any of the supported value types for entity fields. Similarly, [Something] lists in the entity schema are represented as Array<Value> under the hood.

When you access `contractInfo.tokens` it converts that from Array<Value> to Array<ID> by making a copy of the array and converting each value, so `contractInfo.tokens.push(eip721Token.id)` is pushing to a copy of the array. 

The suggested pattern is to: 1. access the array and create the copy, 2. push your new item to it, 3. save the updated copy back to the field. 
```typescript
const tokens = contractInfo.tokens
tokens.push(eip721Token.id)
contractInfo.tokens = tokens
```

**Comment by wighawag** [comment]
Tried your suggestion (see https://github.com/wighawag/eip721-subgraph/commit/1dd7dc56e6db97f98dff46fc731fddbee273d5d5)

but get exact same error

**Comment by wighawag** [comment]
Thanks @fordN for the help, as you mentioned on our chat, the issue was about null values.
It is fixed via https://github.com/wighawag/eip721-subgraph/commit/2311f3eb385b27c5a84898aee57a31b4b53991bc
