### ISSUE TITLE
Stop, pause, and resume

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#168]
Since syncing takes a long time it's a bad DX to have to restart syncing every time you stop the node.

- Make sure we don't duplicate database operations when restarting the server
- What happens if parameters changes between invocations?

**Comment by yanivtal** [comment]
Depends on #235

**Comment by leodasvacas** [comment]
Assigning to @timmclean since he's doing #235

**Comment by timmclean** [comment]
I believe this is mostly covered by the new block ingestion/event streaming design. "Stop" can be accomplished with the `kill` command, which should be safe due to the use of transactions. "Resume" happens when the node is started again, and it will automatically pick up from the last processed block for each subgraph. Mappings won't be run twice or anything like that.

Changing from testnet to mainnet or vice versa without clearing the DB will, uh, do fun things. Proposed enhancement: detect impossibly large reorgs and panic with an error message informing the user that they switched networks without changing the network name parameter.

**Comment by Jannis** [comment]
@timmclean What we have in mind for stop/pause/resume as for them to be possible without restarting the node at all. E.g. you'd send a "pause" or "resume" command to the admin JSON-RPC API and it would pause any further blocks/events/transactions from being processed in a subgraph.

You're right thought that killing the process and starting it again should be similar to stop/pause followed by resume.

What is the testnet to mainnet comment referring to?

**Comment by Jannis** [comment]
We don't this feature right now.
