### ISSUE TITLE
Add tuple[] support for event and call handlers 

### ISSUE THREAD

**Issue by hilmarx** [graphprotocol/graph-node#1800]
**Do you want to request a feature or report a bug?** 

`Feature`

**What is the current behavior?**

Event Handlers that emit nested `tuple[]` do not get called in `mapping.ts` and the respective logic not executed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

This event is special because it emits multiple nested tuple arrays, which you can find here:

https://github.com/gelatodigital/gelato-core-contracts/blob/1712e07b22fd0e753539599cfe99680e2715575e/contracts/gelato_core/interfaces/IGelatoCore.sol#L38-L46

The event that emits it, if found here:

https://github.com/gelatodigital/gelato-core-contracts/blob/1712e07b22fd0e753539599cfe99680e2715575e/contracts/gelato_core/GelatoCore.sol#L162

**What is the expected behavior?**

The Event handler should be called as usual and the logic thereon executed and the Entities stored correctly.

**Comment by Jannis** [comment]
Like with https://github.com/graphprotocol/graph-node/issues/1668 and https://github.com/graphprotocol/graph-node/issues/1765 I think the problem is the signature. ethabi/graph-node/graph-cli seem to be representing it as `tuple[]` when it should e.g. be `(uint256,bytes32,string)[]` (i.e. an array of tuples with concrete types).
