### ISSUE TITLE
Blocks processed per minute are throttled to 60

### ISSUE THREAD

**Issue by trader-payne** [graphprotocol/graph-node#1924]
- ### A bit of introduction to my setup and the archive nodes I tried using so far:

**My setup:**
48 cores EPYC / 128GB RAM / RAID0 Storage
Running everything with docker compose on the same machine

**Geth archive node:**
96 cores EPYC / 512GB RAM

**OpenEthereum archive node:**
64 cores EPYC / 256GB RAM / RAID0 Storage

- ### Index-node environment variables used before the tests

![image](https://user-images.githubusercontent.com/10525363/94876135-70743400-045f-11eb-976f-2d4ba66655e5.png)

- ### Tried tinkering with the environment variables while using the Geth node
Played with the following:
```
      ETHEREUM_BLOCK_BATCH_SIZE: 200
      ETHEREUM_RPC_MAX_PARALLEL_REQUESTS: 128
      GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE: 200
```
Saw literally no change in the blocks processed per minute.

- ### I increased the first two variables above by orders of magnitute

Still no change, still capped at 60 blocks per minute

- ### Decided to set them to `zero`

Indexing stopped, so clearly _something_ works as expected, but they seem to be hard capped internally somehow

- ### Swapped to OpenEthereum node and upgraded to the latest builds

![image](https://user-images.githubusercontent.com/10525363/94880829-d3b89300-046c-11eb-94e6-446f49dc3360.png)

- ### Also notice how it syncs multiple subgraphs at once, but all of them are capped at 60 bpm

![image](https://user-images.githubusercontent.com/10525363/94880844-dca96480-046c-11eb-9c2f-c9e22083608f.png)

- ### Last three days of activity (ignore the spikes/restarts as it includes the Geth/OE swap)

![image](https://user-images.githubusercontent.com/10525363/94881052-69542280-046d-11eb-9195-05708fed9dcf.png)

- ### System-wide stats for the past 7 days

![image](https://user-images.githubusercontent.com/10525363/94882368-7fafad80-0470-11eb-9fbd-67d37d6c9755.png)

- ### Docker Host stats for the past 7 days

![image](https://user-images.githubusercontent.com/10525363/94882787-94d90c00-0471-11eb-8474-304c2b4ae86a.png)

----------------------------------------------------------

### NOTES:

- Grafana dashboard that I used for the pics above: 
https://github.com/graphprotocol/mission-control-indexer/wiki/Grafana-Dashboard-Enhancements

-------------------------------------

- Logs from *a few days ago*, using Geth:
https://cdn.discordapp.com/attachments/745259997100900372/760374128174694430/message.txt
https://cdn.discordapp.com/attachments/745259997100900372/760374824571895838/message.txt
The second of the logs was recorded while `GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE` was set to 100,000 (lol)

--------------------------------------

- Logs from *today*, using OpenEthereum without any of the special environment variables set:
[logs.zip](https://github.com/graphprotocol/graph-node/files/5315729/logs.zip)

- Env vars for the index-node used for the above^ log:
![image](https://user-images.githubusercontent.com/10525363/94883332-12514c00-0473-11eb-943a-1177e44a50b0.png)

-----------------------------------------

I can provide more details or info if needed.

**Comment by koen84** [comment]
No fancy graphs, but these findings are what i previously shared on discord and could be relevant.

So *ToTBN subgraph syncs at just under 120 on OE and just under 60 on turbogeth.  I'm phrasing like this, because i'm wondering about that it's a double/half scenario and that seems too coincidental ?

why would there be a different throttle for different providers (which for me are on different indexers) though ?  Why would i not see a spike when i switch ?

5 min interval progression OE : 414 436 449
5 min interval progressions TG : 380 353 397
So, much closer like this.

The 5 min intervals were done like this :
```
./subgraph_overview.sh; sleep 300; ./subgraph_overview.sh; sleep 300; ./subgraph_overview.sh; sleep 300; ./subgraph_overview.sh; 
http post 127.0.0.1:8020 jsonrpc="2.0" id="1" method="subgraph_reassign" params:='{"name": "ianlapham/uniswapv2", "ipfs_hash": "QmWTrJJ9W8h3JE19FhCzzPYsJ2tgXZCdUqnbyuo64ToTBN", "node_id": "graph_node3"}'; sleep 60; 
./subgraph_overview.sh; sleep 300; ./subgraph_overview.sh; sleep 300; ./subgraph_overview.sh; sleep 300; ./subgraph_overview.sh;
```
With ./subgraph_overview.sh being [this script](https://github.com/koen84/Graph-tools/blob/master/extras/subgraph_overview.sh) in my repo.

**Comment by trader-payne** [comment]
@koen84 weird, for me all the subgraphs (including *TBN) sync at the same speed no matter if I'm on OE or Geth (haven't tried turbogeth yet)

**Comment by cryptovestor21** [comment]
Some of my observations on this:

- Setting related environment variables doesn't seem to work, at least with the method I have used to set them. I have modified nearly all the eth node related variables one by one, but it has no noticeable impact on the performance metric we are using in grafana:

 `increase(deployment_block_processing_duration_sum[1m])`

As per @trader-payne this metric seems to cap out at 60blocks/minute. I would expect this metric to vary considerably when changing env variables such as the ones in my startup script below.

I am setting env variables like so (bare metal):

```
node@graph-indexer-clone0:~$ more graph-startup.sh
#!/bin/bash
source $HOME/.cargo/env
cd $HOME/graph-node

export GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE="200"     #default 100
export GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE="2000"               #default 1000
export ETHEREUM_BLOCK_BATCH_SIZE="100"                          #default 50
export ETHEREUM_RPC_MAX_PARALLEL_REQUESTS="128"                 #default 64


cargo run -p graph-node --release -- --node-id gnode0 --postgres-url postgresql:/........
```

I do have some concerns about the metric we have been using as a baselining tool; maybe @koen84 method is a better picture of processing performance, but we need to understand `deployment_block_processing_duration_sum` in more detail in order to confirm or deny this.

**Comment by koen84** [comment]
@trader-payne yeah, the grafana graph at the time of testing was really clear too.  If you want i can get you RPC access to a fully synced turbogeth for further investigating.

**Comment by trader-payne** [comment]
@koen84 that would be great, because with that we'll then have data from all the major archive node versions. 
I'll send you a DM with my ip if you need it. 
Thanks!

**Comment by azf20** [comment]
Thanks @trader-payne closing this as this was resolved separately 🙏
