### ISSUE TITLE
HTTP requests to external endpoints inside handler functions

### ISSUE THREAD

**Issue by gperezalba** [graphprotocol/graph-node#2016]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the expected behavior?**
Is there any way to HTTP request an external endpoint inside a handler function. The objective is to populate a subgraph's schema with information not contained in blockchain. For example a request to another subgraph or another DB.

I've tried importing packages to handle HTTP requests but everything I try throw errors at compile time ('graph build'). I can't even use asyncs functions with awaits.

Thanks in advance

**Comment by leoyvens** [comment]
Generally no, this is not possible because arbitrary network requests are not determinstic. But we plan on having ways to compose with other subgraphs.

**Comment by chrisciszak** [comment]
@leoyvens has there been any change in this approach recently? 

There is a large number of NFT projects using centralized metadata endpoints, without access to it, we cant query on chain NFTs based on the offchain metadata information making the subgraph pretty useless. Dynamic NFTs is a thing now so even though that data is not deterministic, we should be able to have it saved on the subgraph so that we can query data based of it.

**Comment by devarogundade** [comment]
You can look at Molaris stream event webhook
