### ISSUE TITLE
Feature request - returns the last ... entries sorted by a timestamp in ascending order

### ISSUE THREAD

**Issue by krasi-georgiev** [graphprotocol/graph-node#2269]
I asked in the discord channel and it seems that is not possible so opening as a feature request.

for example I want to get the last 100 entries ordered asc by timestamp from this graph
https://thegraph.com/explorer/subgraph/tellor-io/lens-rinkeby?query=NetworkState
it seems like I can only get the first... items and this way they arrive in a reverse order

**Comment by lutter** [comment]
Would it be possible to get the first 100 in descending order and then reverse the entries in the result client-side?

**Comment by krasi-georgiev** [comment]
This is what I am doing now, but imagine 1000 entries this is delays the rendering quite a bit. I think it makes sense to make this possible on the server side to improve performance.

**Comment by lutter** [comment]
Why do you think this would help performance? The server would have to do the exact same thing you are doing, too; there's no good fast way to query this data directly in the manner you need it, and so we'd go through exactly the same steps, and would have to reverse the entries in the response. If it is for rendering, can't you just render the collection of items backwards instead of explicitly reversing them? BTW, I'd be curious to learn more about your use case that makes you render 1000 items.

**Comment by krasi-georgiev** [comment]
Performance was my main concern, but if you think that doing on server side wouldn't help with that then we can close it.
I am now testing different js libraries to display a chart from the results. Not sure if how will the chart scrolling work yet, but it might need to preload a big amount of the data upfront to all pan and zoom.

**Comment by lutter** [comment]
Ok, I'll close this for now. If you end up needing to download a large number of items, please review the last example in the [pagination section](https://thegraph.com/docs/graphql-api#pagination) in our docs.
