### ISSUE TITLE
Support hot deploying a subgraph to a running node

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#227]
If we do deploys through an admin RPC endpoint then the Graph CLI can just be a client over RPC.

**Comment by leodasvacas** [comment]
This + multiple subgraphs have a lot of surface area so I have a bunch of questions on the requirements, from a discussion with @Jannis:

What happens to current CLI support:
- Do we still want to receive subgraphs through the CLI?
- If so, will the CLI support multiple subgraphs?

HTTP endpoint:
- What CLI options do we need for it?
- What will the endpoint be?
- What operations will it support, add/remove/update subgraph?
- Will we use a protocol such as JSON-RPC? 
- What's the payload, simply the subgraph hash?
- What will we do for auth?

Deploy through graph-cli:
- Will we add a subcommand like `graph deploy --node IP_ADDR subgraph.yaml`?
- What parameters and options will it take?

**Comment by yanivtal** [comment]
What happens to current CLI support:
- Yes, let's continue to accept the currently supported CLI arguments
- No, it could be a nice enhancement to allow passing multiple subgraphs on the CLI but it's not necessary for now

HTTP endpoint:
- I think the only CLI option we need for now is the port. We can see if there are more once we get further into implementation
- Operations: add, remove, update, pause, list
   - Right now subgraphs don't have names in the YAML. The naming is handled at the GNS layer. We might need to add support for names to make `update` more ergonomic. It should be possible to just pass a new subgraph hash and have the node stop the old version and start the new one. This can be done naively for now and a separate ticket can track making upgrades more efficient.
- I would recommend [grpc](https://grpc.io/)
- Payload: subgraph hash
- No auth for this first pass. Let's create a separate ticket for this.

Deploy through graph-cli:
- Yes this looks good `graph deploy SUBGRAPH_HASH --node HOST_AND_PORT`

**Comment by Jannis** [comment]
For the admin endpoint: How about GraphQL mutations rather than GRPC? It would require a small amount of work to support mutations in our execution logic but it would align well with our vision.

We could then have an admin schema and could implement the operations through a dedicated resolver.

**Comment by Jannis** [comment]
Regarding the subgraph name: we could take in `--subgraph [OPTIONAL NAME:]IPFS_HASH` and use `graph deploy --node HOST_AND_PORT [OPTIONAL_NAME:]IPFS_HASH` for deploying.

**Comment by leodasvacas** [comment]
I do not think grpc is viable because there is no official Rust implementation or an unofficial one whose maintenance we can trust. I don't know much about GraphQL mutations but it sounds like an option. I've started implementing using json-rpc because it has good crates and it's simple.

**Comment by Jannis** [comment]
I think GraphQL is what we should do but it won't be super quick and we have enough on our plate, so personally I'm fine with JSON-RPC for a first pass.

**Comment by Jannis** [comment]
@leodasvacas I completely forgot about one aspect: we'll want a different GraphQL endpoint (e.g. `/somehash` and `/someotherhash`) for every subgraph that we load. That'll have a bunch of consequences for our GraphQL server but not for the `SubgraphProvider` etc.

I'll think about that part more tomorrow and try to come up with a good design for it.

**Comment by Jannis** [comment]
I've thought about the different endpoints (one per subgraph) more and it really only affects the `SchemaProvider`, `GraphQLServer`, and the GraphQL execution / resolvers.

We'll want to roughly do the following:

## SubgraphProvider / SchemaProvider

We may want to drop the `SchemaProvider` altogether and instead have the `SubgraphProvider` generate the API schema for the subgraph schema and emit it via `SchemaAdded/SchemaChanged/SchemaRemoved(subgraphId: String, schema: Schema)`, including the subgraph ID.

These schema events would then be forwarded to the `GraphQLServer`.

## GraphQLServer

Manage a mapping of subgraph IDs to their schemas. When receiving a POST request, identify the subgraph ID based on the URL path (`/foo` would mean that the subgraph ID is `foo`). Then, send the subgraph ID and the schema along to the GraphQL execution.

When receiving a GET request, do the same: identify the subgraph ID based on the URL path and render GraphiQL so that it's scoped to this particular subgraph.

We may want to serve a super-simple index page with links to the subgraphs that are available.

## Subgraph IDs vs. subgraph names

For this pass, do we want subgraph names to be used purely for identifying subgraphs when deploying, or do we also want to allow those names in URLs? (@yanivtal, do you have an opinon here?)

**Comment by leodasvacas** [comment]
Thanks for this planning effort, I'm starting with a minimal implementation (just `add`, single subgraph) so we can build this incrementally. What's a good default port for the json-rpc server?

**Comment by Jannis** [comment]
@leodasvacas Sounds good, it's probably worth creating several tasks for the incremental steps.

We currently use port 8000 for the HTTP GraphQL endpoint. Let's keep 8001-8019 free for now and use 8020 for the admin server.

**Comment by Jannis** [comment]
Medium to long term we should make these configurable anyway and _perhaps_ choose less popular defaults. 😉
