### ISSUE TITLE
Subgraph fails on event trigger with unclear error

### ISSUE THREAD

**Issue by peripheralist** [graphprotocol/graph-node#2502]
Running a subgraph on a local graph node. The subgraph correctly detects an event but fails to process it with this error:

```
graph-node_1  | May 30 17:58:53.341 INFO 1 trigger found in this block for this subgraph, block_hash: 0x5cee4cfc9420421e0a01e9e72f2b587a2dc79856ae21e91331a042260eef5b17, block_number: 47, sgd: 4, subgraph_id: QmNPLV8VuAbQy6q8UosBhRww4URZ7Lf4gqVh7DZFXZXRMF, component: SubgraphInstanceManager
graph-node_1  | thread 'mapping-QmNPLV8VuAbQy6q8UosBhRww4URZ7Lf4gqVh7DZFXZXRMF-3dfe9afa-7b7a-41e4-be1b-376146cfdbf1' panicked at 'assertion failed: `(left == right)`
graph-node_1  |   left: `-1`,
graph-node_1  |  right: `0`: registering new sigaltstack failed', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/wasmtime-runtime-0.27.0/src/traphandlers/unix.rs:238:9
graph-node_1  | May 30 17:58:53.391 ERRO Subgraph instance failed to run: failed to process trigger: block #47 (0x5cee…5b17), transaction 46294df5d0b88da42976b739297f6aad2ed71e761ef868618ba4aae8df8ae48a: Mapping terminated before handling trigger: oneshot canceled, code: SubgraphSyncingFailure, sgd: 4, subgraph_id: QmNPLV8VuAbQy6q8UosBhRww4URZ7Lf4gqVh7DZFXZXRMF, component: SubgraphInstanceManager
```

**Comment by azf20** [comment]
Thanks @peripheralist ! Are you running the graph-node in a docker container? cc @otaviopace

**Comment by peripheralist** [comment]
Yep, using the docker image from this repo without any changes. Running on a M1 Mac

**Comment by otaviopace** [comment]
@peripheralist I think you'll have to use this Docker tag for now: https://hub.docker.com/layers/graphprotocol/graph-node/2c23cce/images/sha256-9182194b742c2c1a70658f7f01aa49a30a8ecd2353f7ae1e7cfd43be73f7c262?context=explore

If you're using our `docker-compose` just change [this line](https://github.com/graphprotocol/graph-node/blob/master/docker/docker-compose.yml#L4) to:

```yaml
image: graphprotocol/graph-node:2c23cce
```

For some reason images we've built after this hash are breaking on M1 Macs, maybe because of some weird linking issue or something, we haven't figured it out yet.

**Comment by otaviopace** [comment]
You can also compile the source code directly, it is working on M1 Macs, me and @azf20 use them as well 😄 

But since you're already trying with docker, it might be easier.

**Comment by peripheralist** [comment]
I just switched to that Docker tag and problem solved 😄 Thanks for the quick help!
