### ISSUE TITLE
Too many data-sources: Payload is too big to load

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#2616]
When there are too many data-sources, the RPC call fails with "payload too large"

[Affected subgraph](https://thegraph.com/explorer/subgraph/pancakeswap/exchange-lite?version=pending)

Error:
```
Payload is too big to load: Unexpected RPC error, error: Transport("Unexpected response status code: 413 Payload Too Large"), component: BlockStream
```
- [Source](https://github.com/pancakeswap/pancake-subgraph/pull/27/files)

**Comment by tilacog** [comment]
Maybe we can chunk the requests for a large number of data sources?

**Comment by leoyvens** [comment]
Yes here where we build the filters we could chunk by a maximum number of contracts. I wonder how many data sources that subgraph has. This would likely also solve issues we've seen with eth_getLogs requests to BSC taking over 10 minutes to respond.

https://github.com/graphprotocol/graph-node/blob/b6968695b572a73ebfb86028389d16cdf375c32c/chain/ethereum/src/adapter.rs#L240-L263

**Comment by Xunjin** [comment]
Looking into source code with @tilacog, came the idea to instead of buffer about 1000 per API calls to currently go otherwise with 1000 API calls with 10 items, does it make sense ?

https://github.com/graphprotocol/graph-node/blob/b6968695b572a73ebfb86028389d16cdf375c32c/chain/ethereum/src/ethereum_adapter.rs#L660-L684
