### ISSUE TITLE
Improve Ethereum unavailable error

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#269]
When the infura url is invalid we get the following error which does not make it obvious that it is a simple setup fix:
```
web3::transports::ws: WebSocketError: Error(Transport("ResponseError(\"Status code must be Switching Protocols\")"), State { next_error: None, backtrace: None})
```

**Comment by timmclean** [comment]
Suppressing this error might not be possible, amusingly enough. When the WebSocket transport is created (synchronously), Web3 kicks off another thread to establish the connection, and there is no way to get information on any errors that happened in that thread as far as I can tell. Web3 is just [logging the error itself](https://github.com/tomusdrw/rust-web3/blob/master/src/transports/ws.rs#L150).

I'm evaluating some alternatives. I think I might do a test RPC call (`eth_hashrate`) with the newly created transport to find out if it's working, and timeout after, say, 5 seconds if the operation doesn't complete so that I can show the user a better error message. Or maybe I could submit a PR to Web3 to try to improve what info they give us? I'm not sure that it's an easy fix on their end.
