### ISSUE TITLE
Plan implementation for block and event streaming

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#281]

**Comment by timmclean** [comment]
Ford and I had a great discussion about this today, and a few realizations came out of it.

First, the store updates that occur when a mapping is executed should be done atomically within a single transaction. Otherwise, a query might end up seeing entities that are only partially updated to reflect a particular event. It doesn't look like this is handled currently.

Second, we suspect it makes the most sense to make store updates atomic at the block level. So, if one transaction triggers multiple events, then either none of those events or all of those events will be visible to queries, which is less confusing for users.

So, based on the above, I'm thinking that the `EventStream` should group events by block, since this will match what happens in the store.

```rust
// Each EventsUpdate is about a single block
enum EventsUpdate {
    ProcessEvents(Vec<Event>, BlockHash),
    RollbackEvents(BlockHash),
}

// EventStream is a EventProducer<EventsUpdate>
// Note: should we use "Log" to avoid overloading the term "Event"?
```

Another piece that came up is that, currently, the Ethereum adapter pulls all events matching a filter since the beginning of time, so that the mappings have a chance to see every event that might be relevant to them. I don't want to have to produce an `EventsUpdate` for every single block back to the genesis, so I'm thinking that `EventStream`s will be allowed (but not required) to omit updates for blocks that contain no relevant events. This also saves a bunch of processing when getting caught up after a node has been disconnected for a while.

I made an unfortunate discovery today: [`eth_getLogs`](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getlogs) allows filtering with `fromBlock` and `toBlock`, but it requires those values to be block numbers, not block hashes. This seems like a major oversight, since the meaning of "block #N" can change over time. I think this RPC call is only safe to use for block numbers much below that of the latest block -- in other words, blocks that are old enough such that we can assume there will be no reorgs -- otherwise, we can't know what blocks we're actually accessing. For new blocks, we'll have to use the slower, block-by-block approach, checking each block's bloom filter.

---

I'm going to start the implementation tomorrow with a `BlockIngestor` component. It will be a `tokio::timer::Interval` used to poll for latest block via web3. Each poll result will be used following the algorithm from #235:
- upsert into DB
- check for gaps
- update chain.head
- garbage collect
- updates to chain head will trigger `NOTIFY chain_head_update, ${chain_id}`

**Comment by timmclean** [comment]
Some useful posts on how to choose a value for T:
https://blog.ethereum.org/2016/05/09/on-settlement-finality/
https://blog.ethereum.org/2015/08/08/chain-reorganisation-depth-expectations/
