### ISSUE TITLE
Make more data available to mapping handlers

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#294]
We make certain data, like block hash, available to the handlers through the event object. Not all the data developers need is made available though. For example, a common need is access to the txHash. We should spend some time deciding what additional data to make available and how to structure it and then make that change.

One way we could do this is to include the block, transaction, and log data on the event under those respective keys. We could include all the relevant data for each including things like gas price, etc.

**Comment by Jannis** [comment]
Sync with @timmclean to make sure all data that we want to include is either available through the event stream or can be fetched from the database.

**Comment by timmclean** [comment]
Some notes on this:
- I was storing a [`Block<H256>`](https://docs.rs/web3/0.3.1/web3/types/struct.Block.html) type in the DB as JSONB. I changed that to `Block<Transaction>`, so that we can get a list of transaction objects (includes gas price etc) from the block's JSONB, not just transaction hashes.
- The `Log` type from web3 contains the log's transaction hash, so that part is easy
- Full transaction receipts are not part of the web3 [Transaction](https://docs.rs/web3/0.3.1/web3/types/struct.Transaction.html) object. It looks like they have to be loaded one at a time by transaction hash, which seems slow... that's one RPC call per receipt. Need to decide whether to load these lazily (cache in DB) or preload them all when loading blocks.

**Comment by yanivtal** [comment]
I think it would make sense to fetch and store the receipt and logs for each transaction that we store at ingestion time.

**Comment by Jannis** [comment]
Summary for a future development update:
> Until now, there was no way to access the block or transaction that an Ethereum event is included in. We're now making this data available, so that subgraph authors can access e.g. block and transaction hashes, gas statistics and more.
