### ISSUE TITLE
Firehose startBlock before the first available block doesn't start indexing

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#2964]
If the provided startBlock is earlier than the Firehose's first block, the subgraph does not start indexing and hangs

**Comment by sduchesneau** [comment]
The issue was not in client side, but in the firehose.

fixed here: https://github.com/streamingfast/bstream/commit/268abefde7b452b728172a8cc7ac46ec7098a835
deployed to our current prod endpoint with this flag:

--common-first-streamable-block=9820214 (prod)
--common-first-streamable-block=42376923 (testnet)

tested like this:
```grpcurl -H "Authorization: Bearer $SF_TOKEN"  -d "{\"start_block_num\":1234}" mainnet.near.streamingfast.io:443 dfuse.bstream.v1.BlockStreamV2/Blocks```

**Comment by sduchesneau** [comment]
Let me know if this resolves the issue and if it can be closed.

**Comment by azf20** [comment]
Thanks @sduchesneau ! I deployed a `near-mainnet` subgraph with `startBlock: 0` and indexing started smoothly, closing this issue
