### ISSUE TITLE
when syncing, there will be a bug in dozens of minutes

### ISSUE THREAD

**Issue by jlinzhou** [graphprotocol/graph-node#3104]
ERRO Subgraph instance failed to run: Failed to set subgraph status to `failed`: store error: could not read block 76 in file "base/16384/17487": read only 0 of 8192 bytes, sgd: 2, subgraph_id: QmV9rYkQRDo994hbNTH55wUNdeVEQ24tzR5Kcb8Y8eULHq, component: SubgraphInstanceManager

**Comment by maoueh** [comment]
Seems to be an error reported by PostgresSQL directly. You might have corrupted database disk or a problem with your file system/storage devices.

I saw https://stackoverflow.com/questions/56768254/getting-error-8-resource-exhausted-received-message-larger-than-max-15217288/56768255#56768255 that could help. Quite old but describes similar stuff to yours.

Closing since does not seems related to `graph-node` directly, feel free to re-open if you think it's not the case.
