### ISSUE TITLE
About contract calls that depend on archive node

### ISSUE THREAD

**Issue by alberthuang24** [graphprotocol/graph-node#3231]
Hello everyone,
I would like to ask a question, 

Currently, when making a contract call, the block number https://github.com/graphprotocol/graph-node/blob/master/chain/ethereum/src/ethereum_adapter.rs#L508 is specified.

This raises the cost of running the blockchain (archive full node), and I would like to know why such a restriction is needed. Is it just possible that the graph supports querying the data state of some blocks?

Is it possible to provide a lightweight option?

**Comment by maoueh** [comment]
It's required for data integrity and deterministic reprocessing of historical segment. Reprocessing old data to keep data integrity means you need to get the same data at the block height you are currently processing. Imagine processing a transaction that is at block 10 while chain head is 100 000, if you query user's balance, you would get a wrong value or if the account was suicided, just nothing at all. This means wrong data.

This leads to determinism issues. Imagine two indexer indexing a subgraph but a month apart of each other. This means one indexer would have data completely different than the other one because the `eth_call` done by one is would be at HEAD #100 000 but the other one at maybe #200 000 leading to completely different results. This means it would be impossible to ensure that both indexer did the job correctly.

I will close the issue but feel free to continue the conversation.
