### ISSUE TITLE
Fix BigInt comparisons in GraphQL filters

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#331]
This is clearly not the right order:
![image](https://user-images.githubusercontent.com/19324/45213567-317f4e80-b298-11e8-9dbc-a87c3a03a030.png)

**Comment by fordN** [comment]
The current implementation of order_by takes a String to specify the attribute on which the ordering is performed the JSONB attribute is passed directly to the order by clause in the SQL query.    ```.order(
                sql::<Text>("data ->> ")
                    .bind::<Text, _>(order_attribute)```.   The attribute is always passed in as text so the ordering is done in Alphabetic order.  We need to cast BigInt attributes as float using `CAST(data ->> 'attribute' AS FLOAT)` or `(data ->>'attribute)::float`.   

The current `StoreQuery` struct simply provides a string for the order attribute making it difficult to tell the attribute type, we need to pass in a Value enum so that type casting can be done to perform the ordering correctly.

**Comment by Jannis** [comment]
Is float the right thing to do or can we use Postgres' numeric type?

**Comment by Jannis** [comment]
The best thing to do here is to change the `order_by: Option<String>` to `order_by: Option<(String, ValueType)>` where the `ValueType` matches the values we support in entity attributes.
