### ISSUE TITLE
Identify and fix "failed to lookup address information" error

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#333]
```
CRIT  SepNode error 0, 7 10location:36::06.349  libcore/result.rs:945DEBG,  errorfind:,  sqlcalled `Result::unwrap()` on an `Err` value: RpcError(Error(Transport("Io(Custom { kind: Other, error: StringError(\"failed to lookup address information: nodename nor servname provided, or not known\") })"), State { next_error: None, backtrace: None })):
```

**Comment by timmclean** [comment]
Pretty sure this is a user-side network connection issue, can be solved for now by rerunning the node. More robust retrying around RPC calls would be helpful, then this could be only a warning.

**Comment by Jannis** [comment]
@timmclean Rerunning the node isn't really an option. We will need to retry here.

**Comment by timmclean** [comment]
Ah right, I keep forgetting that we're hosting the node. There's a 50% solution to this problem in https://github.com/graphprotocol/graph-node/commit/90932b979536ae4c7f9f4199bf7f8478198126b2 . To fix the transaction receipt loading issues, I made web3 errors log a warning instead of panicking. It doesn't immediately retry, but it retries on the next head block update, which is pretty often

**Comment by Jannis** [comment]
Let's keep an eye on this and revisit when we encounter it again.

**Comment by timmclean** [comment]
I think the best solution to this is https://github.com/graphprotocol/graph-node/issues/389, putting retries on all web3 calls in the Ethereum adapter

**Comment by Jannis** [comment]
Yep, agreed.
