### ISSUE TITLE
Make sure `Store::get` is executed in the correct order

### ISSUE THREAD

**Issue by leodasvacas** [graphprotocol/graph-node#342]
Our `Store::set` calls are put in a queue to be queried, however our `Store::get` calls (currently on the `ethberlin` branch) do not respect the queue, we should make sure they do.

**Comment by timmclean** [comment]
Sounds good. This would be StoreTransaction::get/set though, right? I was thinking Store::get/find shouldn't see data from pending store transactions until they are committed

**Comment by leodasvacas** [comment]
I'm not sure how `StoreTransaction` will work, but the motivation for this issue is to make sure that, in a mapping:
```
store.set('Entity', id, x)
let y = store.get('Entity', id) 
assert!(x, y)
```
Is always true, because we make sure the effects of the `set` are visible to the `get`.

**Comment by timmclean** [comment]
Makes sense! That was the original idea behind StoreTransaction, but wasn't implemented yet, since we didn't have store.get available to the mappings yet. Basically, we don't want any of the store set/delete commands from the mappings to hit postgres until an entire block has completed processing, but we still want mappings to see the effects of prior set/delete commands. I think @Jannis had a new approach in mind for handling that though.
