### ISSUE TITLE
#3476 - Reopen issue with derivedFrom fields 

### ISSUE THREAD

**Issue by steegecs** [graphprotocol/graph-node#3497]
Thank you for taking care of the issues from #3476. However, There still seems to be an issue with the derivedFrom fields. A member from the graph discord pointed it out to me. 

if you go to: 
https://thegraph.com/hosted-service/subgraph/steegecs/uniswap-v2-bytes
and type in the query: 
``` graphql
{
  liquidityPools {
    deposits {
      id
    }
    withdraws {
      id
    }
    swaps {
      id
    }
  }
}
```

The derivedFrom appears to work for swaps often, however, it is not working for deposits and withdraws. I checked some of the the of fields that use derivedFrom in the subgraph, and they seems to work. 

The code for this subgraph deployment can be found here:
https://github.com/steegecs/subgraphs/tree/steegecs/uniswap-v2-BytesTest/subgraphs/uniswap-v2

**Comment by lutter** [comment]
I just checked in the database, and all the `Withdraw` and `Deposit` entities have `pool` set to `\x00000000`, so there's no `LiquidityPool` that matches them. Checking [`createDeposit`](https://github.com/steegecs/subgraphs/blob/steegecs/uniswap-v2-BytesTest/subgraphs/uniswap-v2/src/common/creators.ts#L137-L172) I don't see the pool of the new entity being set.

It's not entirely clear why the `Bytes` field `pool` on new entities is all zeroes instead of `null`, but I think that's a different issue. That might be getting initialized to a `0u32` (cc @evaporei ) through generated code - and that initialization circumvents the check that the field is not null.

**Comment by steegecs** [comment]
Oh! My bad. I missed that I was not populating the pool ID. I added the pool id for the deposits and withdraws. As you'd expect, it is working now!

Yeah - I would have expected that it would throw an error or warning if pool is null since it was required. 

Thank you again for checking into this!

**Comment by lutter** [comment]
Closing according to last comment
