### ISSUE TITLE
Grafting does not respect deterministic failed status

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-node#3501]
To reproduce:
1. Have a subgraph fail with a deterministic error at block N.
2. Graft it at block N.
3. The grafted subgraph will continue syncing from N + 1, when it should be failed at block N.

**Comment by evaporei** [comment]
The `graft` feature always starts from the `base` subgraph at block N + 1. Upon testing the described scenario on `graph-node` version `0.24.2`, I bumped into this error message:

```
✖ Failed to deploy to Graph node http://127.0.0.1:8020/: subgraph validation error: [the graft base is invalid: failed to graft onto `QmWt3quQnYFhwypj93Uco7ex3UmtdeRrLAhYY5cbQL2Vn6` at block 11416275 since it has only processed block 11416241]
```

Which makes sense, because it was only on `0.25.X` that `graph-node` started processing deterministic failures (saving the deployment pointer).

My proposal is to validate at creation time, just like the error above, that subgraphs can't be created at the failed block, because `graft`s start at N + 1.

If a developer wishes to reproduce the failure in a graft, they should define in their manifest block N - 1 (N being where the base failed). We can give a nice error message in the validation suggested above 🙂 

What do you think @leoyvens ?

This is where the failure happens for the curious ones: https://github.com/graphprotocol/graph-node/blob/master/graph/src/data/subgraph/mod.rs#L478
