### ISSUE TITLE
Directive to support pluralizing names

### ISSUE THREAD

**Issue by saihaj** [graphprotocol/graph-node#3574]
Today in subgraph schema definition if you use word like `metadata` as an entity name it will not generate a plural for the query that can return a list of items is not generated. This is potentially because there is no plural for that word that can be generated. 

It would be nice if `@entity` directive could support taking an argument to which we can give a name for what to name plural type.
```graphql
@entity(plural: String)
```

**Comment by psparacino** [comment]
Bumping this one. Very relevant to fix! Just torched ~90 mins on this one.

Probably will take a look myself later on as this issue doesn't look like it got any attention.

**Comment by paymog** [comment]
Bump

**Comment by azf20** [comment]
> This is potentially because there is no plural for that word that can be generated.

@lutter @saihaj is this indeed what is happening? What is the underlying logic?

**Comment by lutter** [comment]
Since I am deep into that code, I am changing it so that if an entity type has a name whose plural is identical we add `_collection` to the name; for example, if you have entity type `Stats`, we would then have `stats` for single-entity queries and `stats_collection` for the collection. (I was very tempted to make that `stats_but_plural` but that might not be the best UX :wink:)
