### ISSUE TITLE
yarn deploy-local failed at last step

### ISSUE THREAD

**Issue by tomy-tang** [graphprotocol/graph-node#3595]
**Do you want to request a *feature* or report a *bug*?**
*bug**

**What is the current behavior?**
Failed to deploy to Graph node http://127.0.0.1:8020/: subgraph resolve error: resolve error: This Graph Node only supports manifest spec versions between 0.0.2 and 0.0.4, but subgraph `xxxxx` uses `0.0.5`
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I have the specVersion: 0.0.3 in the subgraph.yaml. after I deploy-local, the error message is above and the specVersion modified to 0.0.5 
**What is the expected behavior?**
should not change the specVersion or show what cause this specVersion update, then I can fix it.

**Comment by azf20** [comment]
Hi! This is because automigrations were applied in the latest graph-cli version which are not yet supported by graph-node (0.26.0). The latest graph-cli (0.30.1) fixes these automigrations, so graph-node should be happy. If you want to use features that are only available with specVersion 0.0.5, you can use the most recent graph-node docker tag, but be warned that this is not a stable released version. Closing, thanks!
