### ISSUE TITLE
Reverting a block is slow after merging the block ingestor

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#370]
This causes the test suite to spit out warnings like these:
```
test revert_block ... test revert_block has been running for over 60 seconds
test revert_block_with_delete ... test revert_block_with_delete has been running for over 60 seconds
test revert_block_with_partial_update ... test revert_block_with_partial_update has been running for over 60 seconds
test update_existing ... test update_existing has been running for over 60 seconds
```

Our theory here is that it's only `revert_block` that takes ages and that something that we introduced in https://github.com/graphprotocol/graph-node/pull/363 is causing this.

**Comment by timmclean** [comment]
Is this on master? I just ran `cargo test` on master and it completed just fine

```
test get_entity ... ok
test insert_entity ... ok
test partially_update_existing ... ok
test revert_block ... ok
test revert_block_with_delete ... ok
test revert_block_with_partial_update ... ok
test update_existing ... ok

test result: ok. 44 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by leodasvacas** [comment]
I'm pretty sure I got this before #363, might be worth bisecting for the cause. If @timmclean can't reproduce then it might be an environment thing, on Travis the test passes in under 60 seconds, though I can also reproduce it.

**Comment by fordN** [comment]
I also have not been able reproduce yet on either of my machines.  My Postgres setup is potentially different as I am using a Kubernetes cluster; I am going to try a direct install of Postgres.

**Comment by fordN** [comment]
We have been making changes to the Postgres migrations in place, so in many cases diesel will not apply new changes to an existing database.  Abnormal behavior could be the result of out of date stored procedures or table schema on the test database.  Changing the migrations in place makes for a cleaner codebase and git history, but at some point we should stabilize and only make changes in new migration folders. 

I also noticed that we have triggers for updating the history tables as well as for sending out notifications of entity changes.  The triggers key off of identical events to the `entities` table, so we could integrate the pg_notify() function into the already existing history trigger functions in order to reduce the number of triggers sent and trigger functions called.

**Comment by Jannis** [comment]
@fordN On the second remark: Do you think having fewer triggers would make a difference? I suspect `pg_notify` is much more expensive than triggering, so even if we were to merge e.g. the entity change `pg_notify` into an existing trigger, my assumption would be that things wouldn't improve much.
