### ISSUE TITLE
GraphQL queries return errors instead of results

### ISSUE THREAD

**Issue by nenadjaja** [graphprotocol/graph-node#385]
**Do you want to request a *feature* or report a *bug*?**
A Bug

**What is the current behavior?**
Running GraphQL queries for some entities returns an error: `"message": "Null value resolved for non-null field: auctions"`. It should return an empty array or something similar if there are no matching entries.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
It's happing for this subgraph: https://github.com/graphprotocol/wurstauction/tree/master/subgraph, when I run for example, the following query in the GraphQL interface:
`{
  bids  {
     id
  }
}
`

**What is the expected behavior?**
It should return the bids.

**Comment by Jannis** [comment]
There are at least two ways to cause this to happen:

1. Forget explicitly setting the `id` attribute of an entity with `entity.setString('id', ...)`. This is easy to solve: we shouldn't require the `id` to be set, since it's also passed to `store.set`. This is tracked in #386.
2. Setting a reference field (e.g. `Bid { auction: Auction! }`) to a value that doesn't match an existing entity.

Number 2 isn't trivial. We _could_ try to check whether references are valid as part of `store.set`. This would require roundtrips to the database and thus, make writing to the database slower. It would also make the upcoming `ChainStore::transact` (applying multiple entity operations for a subgraph at once) harder to implement. But it's an option.

Other improvements that I suggest we implement:

1. Add an extensible validation step in `store.set`. Verify that reference field values are strings, not U256 or anything else.
2. Generate AssemblyScript types for types in the GraphQL schema, so that developers can use `bid.auction = 'string'` in a type-safe way, with the compiler complaining if you try to set a value that's not a string.
3. Improve the GraphQL error message. If reference fields (any of `Auction!`, `[Auction]!` and `[Auction!]!`) resolve to null, make the error something like
   ```
   Reference from Bid <ID> to Auction could not be resolved.
   The value of the "auction" field is null.
   ```
   and
   ```
   Reference from Bid <ID> to Auction could not be resolved.
   The value of the "auction" field is: <ACTUAL VALUE HERE>.
   ```
   etc. Reference lists and derived references are a bit more complicated but we can still return more useful errors for them, like:
   ```
   References from Auction <ID> to Bids could not be resolved.
   There are no Bids matching the value of the Auction's "id" field.
   ```

**Comment by azf20** [comment]
I have encountered this issue. I think what is complicated is that it's an opaque query-time error, where the problem is that the linked entity wasn't populated correctly in the database during indexing. Rather than applying checks to `store.set` at indexing time, do we need to throw this error at query time? From a developer perspective it would be easier to debug from a null field in the query response (rather than this error)

**Comment by azf20** [comment]
@nenadjaja do you think this is the same as https://github.com/graphprotocol/graph-node/issues/953?

**Comment by saihaj** [comment]
Looking at the subgraph schema, it is expected to return this error. We should rather update the schema this way we can be sure that we will return an empty array.

```graphql
  bids: [Bid]! @derivedFrom(field: "auction")
```
