### ISSUE TITLE
Make the config.toml file more modular by expanding env vars inside it

### ISSUE THREAD

**Issue by trader-payne** [graphprotocol/graph-node#3946]
**Do you want to request a *feature* or report a *bug*?**
Feature request

**What is the current behavior?**
Only some of the parameters can be inserted via env vars

**What is the expected behavior?**
Similar to  https://github.com/graphprotocol/graph-node/commit/b82ac37784db19261f200b3b3720acd010a3ed19 but for pretty much anything there is to set inside the toml file.

Example:
```
[chains.${CHAIN_0}]
shard = "${SHARD_0}"
provider = [ { label = "${CHAIN_0}", url = "${CHAIN_RPC_0}", features = ["${CHAIN_0_FEATURES}"] } ]```

**Comment by neysofu** [comment]
There's several production-ready tools that perform variable expansion:

- https://www.gnu.org/software/gettext/manual/html_node/envsubst-Invocation.html
- https://github.com/a8m/envsubst (this one is great)
- https://github.com/drone/envsubst

I'd be inclined towards using of of these tools, rather than reinventing the wheel inside `graph-node`. Can you please check if they fit your use case and report back? Thanks :smiley:

E.g. `go install https://github.com/a8m/envsubst@latest && envsubst < graph-node-config.toml.tmpl > graph-node-config.toml`.

**Comment by neysofu** [comment]
We're thinking about adding `envsubst` to the official `graph-node` Docker image, which would hopefully fix this problem for most use cases.

**Comment by trader-payne** [comment]
I've tested it on the host machine and it works wonders! I would love to have this handed off to the graphnode container tho!

**Comment by trader-payne** [comment]
I managed to integrate this into my Testnet Environment completely hands off, but again, this would be so much better to have in the graph-node container 🙏🏻  I think you can close this issue if you want, or keep it open until/if it's ever integrated 😬  Thanks a lot! You saved a lot of headaches during the MIPs program ser lol

**Comment by neysofu** [comment]
I'll keep this open, hopefully we can get this sorted in time for 0.29.0 :)
