### ISSUE TITLE
Investigate non deterministic test failure

### ISSUE THREAD

**Issue by leodasvacas** [graphprotocol/graph-node#401]
[This travis build](https://travis-ci.org/graphprotocol/graph-node/jobs/431062769#L1149) failed the store test `find_string_less` on this assertion:
https://github.com/graphprotocol/graph-node/blob/daba3e88a5fef85f919a872650ed752c88cf9335/store/postgres/tests/store.rs#L491-L495
The returned name was in fact "Cindini".

There is clearly some non-determinism here as this test has always passed before, but this failure is highly suspicious and likely indicates some bug. Perhaps the non-determinism is in the order of the elements in the vector? Assigning @fordN to investigate.

**Comment by fordN** [comment]
The query in `find_string_less_than()` does not use order by which could be the cause of non-determinism since the assertion references the first item in the result list.  

Though the failing test has not reared it's head for me I'd suggest removing the `find_string_less_than` test altogether since we also have `find_string_less_than_order_by_asc`, `find_string_less_than_order_by_desc`, and `find_string_less_than_range`.

**Comment by leodasvacas** [comment]
@fordN sounds good to me. @timmclean do you wanna do that as a subitem of #434?

**Comment by timmclean** [comment]
Oh yeah sure
