### ISSUE TITLE
Ongoing pruning for subgraph deployments

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-node#4159]
Pruning is a useful and desired feature for subgraph developers and indexers, increasing query speed and reducing database size. This issue seeks to make pruning less manual and more programmatic for all parties. This is essential for projects operating at scale, and to overcome communication challenges on The Graph Network.

- [ ] add a “prune me” setting to deployments, storing the number of blocks to prune

Considerations:
- how frequently should deployments be pruned? should that be a separate setting? should that be at the deployment level, or graph node level?
- how can we (/ the operator) ensure that there isn't too much simultaneous pruning which could impact database performance?
- Note: this is a setting at the level of a deployment, rather than at the level of the subgraph. Is that the right decision?

- [ ] add graphman command to set prune me for deployments

```
graphman prune Qm... 10000 --ongoing
```

Considerations:
- we probably want support to add multiple here?

- [ ] add config to the subgraph.yaml to set prune me on a subgraph

```
features:
  - pruning: 100000
```

**Comment by lutter** [comment]
My take on how this will work internally: assume there's a `history_size` attribute for each deployment that can be manipulated with `graphman`. Every time the writer for the deployment transacts changes, it also checks whether the size of the history is bigger than `history_factor * history_size` and prunes if that's the case. I am thinking 1.2 is a good value for `history_factor` to make sure we never have to prune a huge proportion of the data. With relatively little to prune, we can just delete data and don't need to do the whole dance about copying data around that pruning does currently.

With that, ongoing pruning would happen during the normal course of syncing.

When the `history_size` flag is first set on a subgraph with a large amount of history, we'll use the current strategy of copying the data we want to keep, also during the normal sync flow. Whether that needs to be throttled is a good question - we probably do need to limit the amount of concurrent large-scale prunes to limit the amount of IO pressure that generates on the database.

It wouldn't be too hard to add a `history_size` setting to subgraph names, and have the deployment inherit that; since a deployment can be used by multiple names, there's the possibility that the settings for those names conflict. Simplest to implement would be a 'first setting wins' policy.

We should also report the `prune_history` setting through the `index-node` API, and if we make it a per-name setting, some way to find out that setting

**Comment by lutter** [comment]
What I am working on right now is the following:
* add a flag to `graphman prune` to make the amount of history sticky for that deployment
* when the flag is first set, we do a prune-by-copying run while `graphman prune` is executing
* `DeploymentStore.transact_block_operations` will check if we have accumulated more than `history_factor * history_size` blocks of history and then prune-by-deleting. `history_factor` is a global setting from the environment, `history_size` is what gets set with `graphman prune` and will be stored in `subgraphs.subgraph_manifest`.
* Pruning will happen inline with writing to the deployment, so other writes will wait until pruning is done. With the store write pipeline and since we prune relatively small amounts of data, that shouldn't be an issue, but we'll have to test that

Future enhancements:
* allow setting the `history_size` when a subgraph is deployed. For that case, we can skip prune-by-copying since the deployment will initially be empty
* make grafting/copying aware of `history_size` so that copying to a deployment where `history_size` is set only copies the history that is needed instead of all history
* come up with a rules-based system to control what deployments retain how much history by default, so that it's possible to say that all subgraphs called `^small/.*` only keep n blocks of history.
