### ISSUE TITLE
graph node database unavailable error

### ISSUE THREAD

**Issue by mindstyle85** [graphprotocol/graph-node#4287]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**

so im on graph node 0.29 for a while now and until yesterday everything looked ok. Yesterday i did open more allocations than usual, totalling over 30 now while usually it was around 20 or less. I have started getting these:

```Jan 07 09:55:40.157 ERRO Connection checkout timed out, wait_ms: 5000, pool: main, shard: primary, component: ConnectionPool
Jan 07 09:55:41.257 ERRO Error accessing block cache database unavailable, sgd: 227, subgraph_id: QmfUATHE6AvxNnDTFC37s7oJ1cXEs1kEVXGBnoXzNwZG3e, component: BlockStream
Jan 07 09:55:41.328 ERRO Error writing to block cache database unavailable, sgd: 227, subgraph_id: QmfUATHE6AvxNnDTFC37s7oJ1cXEs1kEVXGBnoXzNwZG3e, component: BlockStream
Jan 07 09:56:26.700 ERRO Vacuum of subgraphs.subgraph_deployment failed: database unavailable, job: Vacuum subgraphs.subgraph_deployment, component: JobRunner
Jan 07 09:56:26.700 ERRO Update of `notification_queue_usage` gauge failed: database unavailable, job: Report pg_notification_queue_usage(), component: JobRunner
Jan 07 10:00:02.289 ERRO Connection checkout timed out, wait_ms: 5000, pool: main, shard: primary, component: ConnectionPool
Jan 07 10:00:02.389 ERRO Could not send store event, error: database unavailable, sgd: 227, subgraph_id: QmfUATHE6AvxNnDTFC37s7oJ1cXEs1kEVXGBnoXzNwZG3e, component: SubgraphInstanceManager
Jan 07 10:00:03.137 ERRO Error accessing block cache database unavailable, sgd: 227, subgraph_id: QmfUATHE6AvxNnDTFC37s7oJ1cXEs1kEVXGBnoXzNwZG3e, component: BlockStream
Jan 07 10:00:03.208 ERRO Error writing to block cache database unavailable, sgd: 227, subgraph_id: QmfUATHE6AvxNnDTFC37s7oJ1cXEs1kEVXGBnoXzNwZG3e, component: BlockStream
Jan 07 10:00:26.796 ERRO Vacuum of subgraphs.subgraph_deployment failed: database unavailable, job: Vacuum subgraphs.subgraph_deployment, component: JobRunner
Jan 07 10:00:26.797 ERRO Update of `notification_queue_usage` gauge failed: database unavailable, job: Report pg_notification_queue_usage(), component: JobRunner
Jan 07 10:04:32.996 ERRO Connection checkout timed out, wait_ms: 5000, pool: main, shard: primary, component: ConnectionPool
Jan 07 10:04:34.528 ERRO Error accessing block cache database unavailable, sgd: 227, subgraph_id: QmfUATHE6AvxNnDTFC37s7oJ1cXEs1kEVXGBnoXzNwZG3e, component: BlockStream
Jan 07 10:04:34.611 ERRO Error writing to block cache database unavailable, sgd: 227, subgraph_id: QmfUATHE6AvxNnDTFC37s7oJ1cXEs1kEVXGBnoXzNwZG3e, component: BlockStream```

so payne suggested i add more connections to the db, in the postgres config as well as on graph node which i did (300 max connections and 50 for graph node), that didnt help and the above was still happening. Since it was just one subgraph i decided to remove it, once done, i still get stuck with these:

```Jan 07 11:42:18.782 ERRO Connection checkout timed out, wait_ms: 5000, pool: main, shard: primary, component: ConnectionPool
Jan 07 11:42:27.339 ERRO Vacuum of subgraphs.subgraph_deployment failed: database unavailable, job: Vacuum subgraphs.subgraph_deployment, component: JobRunner
Jan 07 11:42:27.339 ERRO Update of `notification_queue_usage` gauge failed: database unavailable, job: Report pg_notification_queue_usage(), component: JobRunner
Jan 07 11:42:45.769 ERRO failed to record unused deployments, error: database unavailable, job: Record and remove unused deployments, component: JobRunner
Jan 07 11:43:01.685 ERRO Connection checkout timed out, wait_ms: 5000, pool: main, shard: primary, component: ConnectionPool
Jan 07 11:43:27.341 ERRO Vacuum of subgraphs.subgraph_deployment failed: database unavailable, job: Vacuum subgraphs.subgraph_deployment, component: JobRunner
Jan 07 11:43:27.341 ERRO Update of `notification_queue_usage` gauge failed: database unavailable, job: Report pg_notification_queue_usage(), component: JobRunner
```

also to note i see these on the indexer service:
``` "message": "[GraphQL] Store error: database unavailable",
            "message": "Store error: database unavailable"
```

It looks like it happens once in a while (lets say every 5-10min) and besides that the subgraphs are still syncing, and the queries are also flowing, so unsure if database might be corrupted or something

**Comment by mindstyle85** [comment]
we have analyzed the db and postgres and found no issues, and finally fixed it:

so the fix was to manually launch vacuum (VACUUM FULL;) 

besides that we also increased the effective_cache_size setting but that one alone didnt solve it

Given the manual vacuum worked and the graph-node was unable to do it, im expecting this might after all be a graph-node issue given that postgres alone was looking healthy on our side

cc @fordN

**Comment by mindstyle85** [comment]
so after 2 days, the vacuum issue is back on the graph-node while again it looks like the postgres is healthy..

**Comment by lutter** [comment]
It's very likely that you are running out of database connections; what are the values for `max_connections` in your `postgresql.conf` and how are the connection pools for your `graph-node` instances configured?

The Prometheus metric `store_connection_wait_time_ms` that `graph-node` emits can be very helpful here - if that is high (I'd say more than 2ms) you most likely don't have enough connections in your connection pool.

**Comment by mindstyle85** [comment]
im not sure, ive set max connections in postgres to 300 and for graph-node ive set them at 50 as payne suggested, but even after that we had those errors. 

I must say that the vacuum issue has disappeared on its own now and it has been fine ever since sunday or so.. I will check those store connection wait times though and keep an eye out in the future, especially if that error comes up again

**Comment by lutter** [comment]
If you only have one `graph-node` running, you should set the pool size to 300, too. You basically want the sum of the pool sizes for all `graph-node` instances to be the same as `max_connections` for Postgres.

The fact that this usually happens with `vacuum` is likely a red herring - it could happen with any operation that needs to talk to the database.

The `subgraph_deployment` table can become bloated and a `vacuum full` is the way to remove that bloat. It's a bit of a sensitive operation since it will block any indexing or querying operation while it runs - that's ok if the `vacuum full` only takes a few seconds, but something to watch carefully.

A big reason why `subgraph_deployment` can get bloated is long-running queries. If you haven't already, you might want to set `GRAPH_GRAPHQL_QUERY_TIMEOUT` and `GRAPH_SQL_STATEMENT_TIMEOUT`. Even with that, you can run into long-running queries since they don't restrict database operations used for indexing (we don't really have a choice there, since we have to run them), but they will at least avoid that bad/slow GraphQL run for unlimited amounts of time.

To better detect whether `subgraph_deployment` is bloated, I have a dashboard that shows the result of this query:
```sql
select u.relname,
       u.n_live_tup, 
       u.n_dead_tup, 
       u.n_dead_tup::numeric/nullif(u.n_live_tup,0)::numeric as bloat_factor, 
       c.relpages,
       age(now(), greatest(u.last_autovacuum, u.last_vacuum))::text last_vacuum
  from pg_stat_user_tables u, pg_class c
 where u.schemaname in ('subgraphs','public')
   and u.relid = c.oid
   and u.n_dead_tup > 100
```
The thing to look at is the number of `relpages` that this returns - it indicates how big that table is (a page in Postgres is 8k)

**Comment by mindstyle85** [comment]
oh this is some great info @lutter !!! im not sure if any of this is somewhere in the docs/academy but i think its worth putting some of it there for when others run into the same problem (and ill also change some things based on what you said above, thanks)

**Comment by mindstyle85** [comment]
@lutter what would be some suggested settings for GRAPH_GRAPHQL_QUERY_TIMEOUT and GRAPH_SQL_STATEMENT_TIMEOUT?

**Comment by lutter** [comment]
@mindstyle85 Sorry, this completely fell by the wayside. On the hosted service we are behind a load balancer that terminates connections after 100s, so we have these set to 105s. The right value depends a lot on what sort of traffic you want to support. If it's mostly dApp traffic (i.e., people looking at web pages) I think 2-3 minutes is a good upper bound, since users will lose interest before then if the data they want hasn't shown up yet.

**Comment by mindstyle85** [comment]
thanks for your help @lutter !

**Comment by aasseman** [comment]
@lutter please allow me to necro this conversation :grin: 

So I've been experiencing this issue on and off, and I have trouble understanding the reasons...
Some numbers:
- 6 graph-node instances
- pool_size=20
- PG's max_connections=273
- Observed total connections: 125
... And yet, I have 2 out of the 6 graph-nodes that complain about not being able to connect to postgres.

Why would graph-node have trouble connecting, since I'm using only half the connections?

**Comment by lutter** [comment]
@aasseman There's two reasons why we report 'database unavailable:

* errors when getting a connection. We log `Postgres connection error` for that
* timeouts when getting a connection. We log `Connection checkout timed out` for that

With your config, `graph-node` will use about 6*20 = 120 connections total (there's one additional one that each graph-node uses for listening to notifications) So with your config, you won't ever use more than the connections you have. You might want to check `pg_stat_activity` and see how many of them are idle at any given time. You should also check the Postgres logs for any errors there besides the graph-node errors I mentioned above.
