### ISSUE TITLE
Support __typename meta field on entities

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#431]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The `__typename` meta field is a way for clients to request the type name of an entity as part of the query. However, we don't currently support it.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the behavior**

Deploy e.g. the Decentraland subgraph, then query
```graphql
{
  parcels {
    id
    __typename
  }
}
```

**What is the expected behavior?**

All entities from the query result should have a `__typename` field set to `"Parcel"`.

**Comment by wip-abramson** [comment]
Would be good to have!

I ran into this issue because ApolloClient v2 uses InMemoryCache which automatically defaults to adding __typename to the query and then complains that this field is empty.

You can turn this off using a config like this:
const apolloClient = new ApolloClient({
  link: new HttpLink({
      uri: "http://127.0.0.1:8000/cli/graphql",
    }),
  cache: new InMemoryCache({
    addTypename: false,
  })
})

Check out the apollo [docs](https://www.apollographql.com/docs/react/advanced/caching.html)

**Comment by leodasvacas** [comment]
Re-opening since the implementation caused other issues, see [these comments](https://github.com/graphprotocol/graph-node/pull/554#issuecomment-441284100) on the PR.
