### ISSUE TITLE
Limit wasm module memory page count

### ISSUE THREAD

**Issue by timmclean** [graphprotocol/graph-node#436]
This would be a good idea for limiting denial of service attacks, but also I suspect there are some determinism issues around `memory.grow()`. It's not clear from the documentation, but it seems like running `memory.grow()` in a mapping might fail sometimes due to external circumstances (e.g. system out of memory), which could lead to non-deterministic behaviour in mappings. We should pick a good memory limit for mappings, and then guarantee to mappings that `grow` will always succeed up to that limit and always fail after that limit.

**Comment by Jannis** [comment]
@leoyvens What does this look like with cranelift today?

**Comment by leoyvens** [comment]
We can't really always guarantee that `grow` will succeed because that depends on the memory available to the system. I checked that we do not consider that to be a deterministic error. The current limit is implied by the 32 bit address space of WASM, and I don't think we want to impose a tighter limit on a protocol level. We might want to allow indexers to configure tighter memory limits, but this hasn't come up as a necessity so far. Closing, to be reopened if this ever becomes necessary.
