### ISSUE TITLE
[Bug] Spurious issue with subgraph deployments

### ISSUE THREAD

**Issue by paymog** [graphprotocol/graph-node#4724]
### Bug report

We have an end to end test suite which does many subgraph deployments. We're find that our tests spuriously fail with `subgraph validation error: [the specified block must exist on the Ethereum network]`. In our test suite, we always deploy subgraphs with against mainnet with start blocks in the range of 0-100. 

We can't reliably reproduce the issue but do find it happens often on different tests. Our API calls the `subgraph_deploy` on graph node and this is the full message that's returned: `subgraph validation error: [the specified block must exist on the Ethereum network]`.

We're running graph node v0.31.0. 

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by paymog** [comment]
Found some relevant logs from our e2e tests:

```
e2e-tests-graph-node-1   | Jul 07 07:50:18.580 INFO Received subgraph_create request, params: SubgraphCreateParams { name: SubgraphName("cljsa19l3001jc6joh17r1gq4") }, component: JsonRpcServer
e2e-tests-graph-node-1   | Jul 07 07:50:18.588 DEBG Created subgraph, subgraph_name: cljsa19l3001jc6joh17r1gq4, component: SubgraphRegistrar
e2e-tests-graph-node-1   | Jul 07 07:50:18.590 INFO Received subgraph_deploy request, params: SubgraphDeployParams { name: SubgraphName("cljsa19l3001jc6joh17r1gq4"), ipfs_hash: DeploymentHash("QmX2wBD6mB5CcqXkp9XP1HfF9LrdKwFSA5eddXVj8sYSTB"), node_id: None, debug_fork: None, history_blocks: None }, component: JsonRpcServer
e2e-tests-graph-node-1   | Jul 07 07:50:19.164 ERRO subgraph_deploy failed, params: SubgraphDeployParams { name: SubgraphName("cljsa19l3001jc6joh17r1gq4"), ipfs_hash: DeploymentHash("QmX2wBD6mB5CcqXkp9XP1HfF9LrdKwFSA5eddXVj8sYSTB"), node_id: None, debug_fork: None, history_blocks: None }, error: ManifestValidationError([BlockNotFound("100")]), component: JsonRpcServer
```

Which is very unusual because block 100 definitely exists on `mainnet` which is the network that this subgraph is being deployed against. We also see that this test often succeeds.

**Comment by azf20** [comment]
hey @paymog could you possibly run with `TRACE` logging in case there is more info on where this is failing?

**Comment by paymog** [comment]
> hey @paymog could you possibly run with `TRACE` logging in case there is more info on where this is failing?

Totally, how do I do that? I searched for [`TRACE` in MD files](https://github.com/search?q=repo%3Agraphprotocol%2Fgraph-node+trace+language%3AMarkdown&type=code&l=Markdown) and don't see mentions of an env var which controls that.

**Comment by sduchesneau** [comment]
The error from firehose is eaten up and there is no retry mechanism.

https://github.com/graphprotocol/graph-node/blob/27cbcdd0cc21bd9a22e604bf18fd0f6b6c8dc37e/graph/src/firehose/endpoints.rs#L387

Error could be one of:
1) network connection issue
2) TooManyRequests (backoff mechanism when getting a burst of connections)
3) server shutting down between the request and the response (ex: due to autoscaling)

IMHO, the IPFS call is made with a retry, I don't see why the "get_block" from firehose shouldn't also be done with a retry mechanism.

**Comment by sduchesneau** [comment]
This is where the (legitimate?) error gets replaced by "Block Not Found":
https://github.com/graphprotocol/graph-node/blob/27cbcdd0cc21bd9a22e604bf18fd0f6b6c8dc37e/core/src/subgraph/registrar.rs#L527

The fetch block should be 1) retried (2 or 3 times is more than enough) and the error should bubble up (ex: connection error...) instead of being replaced by a BlockNotFound.

**Comment by azf20** [comment]
good catch @sduchesneau!
