### ISSUE TITLE
[Bug] blockHashFromNumber on Indexing Status API is returning null since 0.32.0

### ISSUE THREAD

**Issue by chriswessels** [graphprotocol/graph-node#4880]
### Bug report

This query:

```
query {
  blockHashFromNumber(network: "mainnet", blockNumber: 18021810)
}
```

Returns a valid block hash in the response on 0.31.0:

```
{
  "data": {
    "blockHashFromNumber": "efc8821d1ae1815b2e07494945064f5a2e8c5aeadb185d81b708964fc9305a12"
  }
}
```

However on 0.32.0, it returns:

```
{
  "data": {
    "blockHashFromNumber": null
  }
}
```

### Some information to help us out

- [X] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by incrypto32** [comment]
@chriswessels could you post some accompanying logs from the `index-node` you are querying?

I could not reproduce this on an `index-node`, though the result would be a `null` on query nodes since they dont connect to the networks directly.

The other possibility is that `0.32.0` introduced a 10sec timeout not sure if the request take more than that. Does it?

**Comment by azf20** [comment]
Closing, please re-open if you're still seeing this issue @chriswessels
