### ISSUE TITLE
depoly graph failed  graph deploy --studio nftmarkethub --ipfs http://127.0.0.1:5001

### ISSUE THREAD

**Issue by qiaopengjun5162** [graphprotocol/graph-node#5555]
### Bug report

graph deploy --studio nftmarkethub --ipfs http://127.0.0.1:5001
<img width="989" alt="image-20240719161346275" src="https://github.com/user-attachments/assets/f49bb7c6-1e7b-42f2-8966-b78314b3e7fc">

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by Gkok-king** [comment]
in same case

**Comment by qiaopengjun5162** [comment]
graph --version
@graphprotocol/graph-cli/0.78.0 darwin-arm64 node-v22.1.0

**Comment by qiaopengjun5162** [comment]
<img width="780" alt="image-20240720105810386" src="https://github.com/user-attachments/assets/78b72589-e050-4028-aa7f-7f82df7a5e18">

Help, someone help me, I've been stuck here for 2 days

**Comment by mitchhs12** [comment]
Hi @qiaopengjun5162,
This issue is affecting many subgraphs and seems to be related to how the deployment router is used to interact with graph-node to deploy subgraphs. While we continue to work on this issue and implement a fix for this, you can monitor the status of this issue here: https://status.thegraph.com/ and once it has been fixed it will be updated.
You can also raise any other or additional tech support issues you may have in Discord or via the Support button after signing into Subgraph Studio on the website.

**Comment by qiaopengjun5162** [comment]
The problem has been solved, thanks
