### ISSUE TITLE
Define the Postgres data model for subgraph status

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#585]
This includes current block indexing number, current chain head block number and additional fields for the subgraph status.

**Comment by timmclean** [comment]
Proposed design: we add the following fields to the Subgraph entity:
- `status`: enum with the following values:
  - `CATCHING_UP`: Initial state for new subgraphs. Valid next states are `ACTIVE`, `FAILED`, and `PAUSED`.
  - `ACTIVE`: Subgraphs spend most of their time here. Valid next states are `FAILED` and `PAUSED`.
  - `FAILED`: When block processing encounters an error. Valid next state is `CATCHING_UP` (if user forces retry).
  - `PAUSED`: Subgraph has stopped processing new blocks. Valid next state is `CATCHING_UP`.
- `processedEthereumBlocksCount`: Updated after subgraph block pointer is updated. The subgraph block pointer is still the trusted source of truth. This value is not guaranteed to be accurate (race conditions, not updated atomically, etc), but usually will be. This number can decrease temporarily in the event of a chain reorg.
- `totalEthereumBlocksCount`: Not stored in subgraph entity. Retrieved at query time from `ethereum_networks` table. Subscriptions can listen for chain head updates from Postgres.

The distinction between `CATCHING_UP` and `ACTIVE` is to help with monitoring system health. It is normal for subgraphs in the `CATCHING_UP` state to be far behind the chain's head block, while it is abnormal for subgraphs in the `ACTIVE` state to be far behind the chain's head block.

The `PAUSED` state covers the "abort" feature that has been discussed, while leaving open the possibility of an "unabort" feature. I propose that subgraphs enter the `PAUSED` state whenever a subgraph's data continues to persist in the database, but the subgraph has no deployment (i.e. no entry in the `subgraph_deployments` table). The `subgraph_remove` JSON RPC method actually works like this already, since we don't do any clean up of subgraph data. It may be that we want a separate `subgraph_pause` JSON RPC method that works like the current `subgraph_remove`, but also sets the status to `PAUSED`, and then rework `subgraph_remove` to actually clean up the subgraph's entity data.

**Comment by Jannis** [comment]
A few comments:

* I'd maybe rename `CATCHING_UP` to `INDEXING` or `SYNCING` and `ACTIVE` to `SYNCED` or `UP_TO_DATE`.
* It may be way easier to write the `totalEthereumBlocksCount` into the subgraph entity as we go, rather than accessing the networks table at query time. It requires knowing which network the subgraph is indexing from etc. — information which we may or may not have.

Everything else sounds good. Let's punt on the `subgraph_pause` method for the moment.

**Comment by timmclean** [comment]
Cool, thanks!

I like `SYNCING`/`SYNCED`. Note that subgraphs will stay in the `SYNCED` state even if it is a block or two behind the head block, so up to date might be overselling it a bit.

`totalEthereumBlocksCount`: I think that works fine. The only downside is that if a subgraph stops being processed by the indexing node for some reason, then `totalEthereumBlocksCount` won't update

**Comment by Jannis** [comment]
@timmclean That's a good point (about the total blocks count not updating). There are two more aspects to consider here:

1. If it isn't written to the subgraph entity, it won't trigger subscription updates. So that would be bad.
2. If a subgraph is skipping blocks (because there are no interesting events) etc. we need to make sure that we still write `totalEthereumBlocksCount`, so the UI updates.

Other than that I'm ok receiving no further updates on the total blocks count after e.g. a subgraph has been paused. The progress information will resume fine when the subgraph is resumed.

**Comment by timmclean** [comment]
Sounds like a plan, let's ship it!
