### ISSUE TITLE
ID is inaccessible if not defined in the schema

### ISSUE THREAD

**Issue by Arachnid** [graphprotocol/graph-node#612]
The database seems to assume that the unique ID of an entity will always be a field called 'id'. If a node defines an ID with another name, that field will not be populated, and the id field will be inaccessible in queries (as it's not mentioned in the schema).

**Comment by Jannis** [comment]
Recent changes in `graph-cli` actually disallow entities without `id: ID!` fields. This is to prevent confusing behavior like you're describing until we have a better solution.

I personally prefer all entities having a specific `id` field instead of having different fields that act as their unique IDs. It makes things more consistent, simplifies debugging subgraphs etc.

If we were to decide to allow any field to act as the ID, my guess is it would be through an `@id` kind of directive on the field. This affects three places:

1. Automatically setting the ID field when calling `store.set`
2. Singular `someEntity(someId: ...) { ... }` queries.
3. Relationships between entities, which currently rely on `id` fields.

**Comment by yanivtal** [comment]
Yes I think it would make sense to allow custom ID's with a directive. I do think it's reasonable though to enforce that entities have unique ID's. We could optionally allow for composite primary keys.

**Comment by leoyvens** [comment]
Closing because this is old and now out of context.
