### ISSUE TITLE
Limit query complexity

### ISSUE THREAD

**Issue by Arachnid** [graphprotocol/graph-node#614]
At present it's very easy to OOM the process by querying, say, every entity of a given type, if there are a lot of them. In order to make a Graph endpoint publicly accessible, there needs to be some kind of limit on the number of entities a query will execute - either by counting operations and terminating a query early if it's reached, by enforcing a result set size limit on queries, or both.

**Comment by leodasvacas** [comment]
I'll list a few approaches to deal with DoSing GraphQL, some of which I found in [this article](https://blog.apollographql.com/securing-your-graphql-api-from-malicious-queries-16130a324a6b):

**Pagination, enforcing maximum page size and query depth**
Pagination should be a priority here, as even well intentioned queries need it and is a first line of defense against DoS. Page size and query depth are straightforward limits that can be enforced.

**Query cost analysis**
Something we plan to have, though that is more complex not only to implement but also for users to tune the ideal complexity limit for their use case.

**Whitelisting**
If you have only a small set of queries that you wish to make publicly acessible, whitelisting is a possible approach, we'd need to consider if we want the graph node to have direct support for whitelisting.

**Timeout for queries**
We could have a configurable timeout for query processing, and if a query times out we'd give a particular http response that a reverse proxy with rate limiting and blacklisting capabilities can use to inform its DoS protection.

We also need to consider how subscriptions might be used as channel for DoSing.

**Comment by Zerim** [comment]
Personally I'm a fan of option 2 or 4. While limiting page size and depth is nice, I think it would be hard to set restrictions that by themselves prevent DOS attacks w/o meaningfully degrading the overall usefulness of the API.

Whitelisting seems like a non-starter since we want these APIs to be consumed by the entire community, and not just the developers that deployed them.

Might make sense to start w/ the timeout approach if that's the cheaper solution, and add query cost analysis to our roadmap. The latter we could probably leverage in the decentralized network as well.

**Comment by Arachnid** [comment]
One  thing to bear in mind with timeouts is that since they're not deterministic, users will have to expect them and cater for them (likely by retransmitting the query - increasing load on the node).  If you can, return partial results.

**Comment by leodasvacas** [comment]
@Arachnid We already have timeouts, but we're doing more here with #869.

**Comment by leodasvacas** [comment]
SInce this issue opened we've limited to 100 the amount of entites that can be queried for a collection, added configurable timeouts and now limiting the query depth and total amount of entities a query can return. There's of course more that can be done such as #851, but this issue can be considered resolved.
