### ISSUE TITLE
Update subgraph entities to include subgraphs, versions and deployments

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#643]

**Comment by timmclean** [comment]
Here's the schema I've been working with:

```
type Subgraph @entity {
    id: ID! 
    name: String!
    versions: [SubgraphVersion!]! @derivedFrom(field: "subgraph")
    currentVersion: SubgraphVersion
    createdAt: BigInt!
}

type SubgraphVersion @entity {
    id: ID! 
    subgraph: Subgraph!
    state: SubgraphState!
    createdAt: BigInt!
}

type SubgraphState @entity {
    id: ID! # Subgraph IPFS hash
    manifest: SubgraphManifest!
    failed: Boolean!
    deployments: [SubgraphDeployment!]! @derivedFrom(field: "id")
    latestEthereumBlockHash: String!
    latestEthereumBlockNumber: BigInt!
    totalEthereumBlocksCount: BigInt!
    entityCount: BigInt! # Computed field, not stored.
}

type SubgraphDeployment @entity {
    id: ID! # Subgraph IPFS hash
    nodeId: String!
    synced: Boolean!
}
```

There are a few deviations from what we had discussed pre-holidays:
- To replace the `subgraphs` database table (which currently houses the subgraph block pointer), I added a `SubgraphState` entity. This entity is distinct from `SubgraphDeployment` in that it continues to exist even when the subgraph is not deployed (e.g. is not in a "current" subgraph version, or is in a paused subgraph). Conceivably these two entities could be combined however.
- I replaced the `status` field with 2 flags (`SubgraphState.failed` and `SubgraphDeployment.synced`) and the existence of an entity (`SubgraphDeployment`). A subgraph can be considered to be `PAUSED` if it does not have a deployment (in this sense, explicitly setting the status to `PAUSED` was redundant information). The `synced` flag is on `SubgraphDeployment` because the question "is this subgraph synced" does not make sense unless the subgraph is deployed.
- `latestEthereumBlockHash` was added in order to move the full block pointer into `SubgraphState`.
