### ISSUE TITLE
Subscriptions in GraphiQL stop working when new version of subgraph is deployed until page refreshed

### ISSUE THREAD

**Issue by timmclean** [graphprotocol/graph-node#647]
In #332, we looked at some causes of subscriptions not returning any data. This issue, however, is specific to the GraphiQL page provided by graph-node.

Reproduce:
- Deploy a subgraph called "test"
- Visit `localhost:8000/subgraphs/name/test`
- Run a subscription query
- Subscription should work and show entity changes
- Keep the GraphiQL browser tab open
- Deploy a modified version of the subgraph to the same subgraph name, "test"
- Return to the GraphiQL page, run a subscription query
- Subscription does not receive any data, despite entities being changed
- Normal GraphQL queries work fine

The problem is caused by the fact that a websocket connection remains open in the GraphiQL page. The subgraph name is resolved to a specific subgraph ID when the websocket connection is opened. This means that when a new version of the subgraph is deployed, queries still work in the GraphiQL interface because name resolution happens separately for each query, but subscriptions won't work until the page is refreshed because the websocket connection is associated with the old subgraph ID on the server side.

**Comment by Jannis** [comment]
An approach for subscriptions made against a subgraph by _name_ could be to have the subscription stream resolver terminate the subscription and close the connection. The most sensible clients are configured to reconnect. Since they are subscribing by name, they would immediately use the new version after reconnecting.

This doesn't work for subscribing by subgraph _IDs_ though. We should probably still close the connection when the subgraph version/deployment with that ID is stopped.
