### ISSUE TITLE
Only update subscriptions once per block

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#685]

**Comment by timmclean** [comment]
I wonder if the subscriptions updating could be implemented in [apply_entity_operations](https://github.com/graphprotocol/graph-node/blob/master/store/postgres/src/store.rs#L591) so that it doesn't need special casing for the subgraph of subgraphs?

**Comment by Jannis** [comment]
True, that could save the overhead of Postgres notifications for all entity changes as well.

**Comment by lutter** [comment]
What I've been shooting for is to add a `block_ticks` method to `Store` that produces a `BlockTickStream`. The GraphQL subscriptions would then use that instead of `subscribe` to trigger updates. Internally, `handle_entity_changes` would receive both kinds of events (entity changes and block ticks) and feed either kind of subscriber with the appropriate data.

That sidesteps the issue of special-casing metadata updates, but does have the disadvantage of generating entity changes that might not be needed, though I have a hard time seeing how we could turn off entity change notifications without pushing some knowledge about current subscriptions into the DB.

The reason why I am putting both entity changes and block ticks into the same notification channel is ordering: I will generate the block tick in `transact_block_operations` (via `pg_notify`) after all the entity change events have been generated. That way, a block tick also means "you've already seen all relevant entity changes" in case we need to deliver something like that with a block tick. For now, `BlockTick` will just be a very simple struct, maybe with the block id/number in it, but mostly for logging purposes.

**Comment by Jannis** [comment]
Just saw this, thanks for the great write-up @lutter!

Trying do to this in `apply_entity_operations` could be problematic for any setup where querying and indexing is handled by different nodes. So I think going through the database for this is the right thing to do.

**Comment by lutter** [comment]
Rebased onto latest master
