### ISSUE TITLE
Newly deployed versions don't always start indexing

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#713]
```
➜  graphprotocol kubectl logs  -f index-node-mainnet-1 | grep -i YKJk
 Jan 25 00:44:02.662 DEBG Received assignment event: Remove { subgraph_id: SubgraphDeploymentId("QmSwnCt6q6b68DcVV546myus82Hs99nM48d46QXPwcYKJk"), node_id: NodeId("index_node_mainnet_1") }
 Jan 25 00:44:29.405 INFO Received subgraph_deploy request, params: SubgraphDeployParams { name: SubgraphName("lutter/the-count"), ipfs_hash: SubgraphDeploymentId("QmSwnCt6q6b68DcVV546myus82Hs99nM48d46QXPwcYKJk"), node_id: Some(NodeId("index_node_mainnet_1")) }
 Jan 25 00:44:48.660 DEBG Wrote new subgraph version to store, subgraph_hash: QmSwnCt6q6b68DcVV546myus82Hs99nM48d46QXPwcYKJk, subgraph_name: lutter/the-count
```

**Comment by timmclean** [comment]
Based on the logging output, I actually suspect all is well. It looks like the new version's hash was the same as the previous version's hash. Although a node ID was supplied in the `subgraph_deploy` request, it would be ignored because an assignment already exists for that hash. No new assignment would be created. The `Remove` assignment event is harmless (it would have been a no-op on this node assuming the hash was assigned to a different node).

I'm going to close -- please reopen if there was evidence of a problem that I'm not accounting for!
