### ISSUE TITLE
Index nodes failing due to "out of shared memory"

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#764]

**Comment by lutter** [comment]
Just to recap what we found out about this: when we select from `entities`, postgres takes an `AccessShareLock` on the `entities` table and each of its indexes. Since we have a large number of indexes (~2500 when this problem occurred), a relatively small number of queries against `entities` will exhaust the space set aside for locks in pg's shared memory.

CloudSQL does not let us bump the `max_locks_per_transaction` setting, which would be the common remedy for this problem. As a first mitigation, we are going to remove indexes for subgraph deployments that are no longer needed (i.e., that are not current or pending versions of a subgraph)

This will alleviate the problem, but not solve it. A more long-term solution will require changes to our database schema so that we do not have one table with a very large number of indexes.
