### ISSUE TITLE
Add support for Solidity structs

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#766]

**Comment by leodasvacas** [comment]
This looks like the relevant ethabi issue https://github.com/paritytech/ethabi/issues/113

**Comment by fordN** [comment]
I still need to find a good example of Solidity Struct usage in a contract in order to create a test subgraph, but after preliminary research I've come up with the following plan: 

### Requirements:

1. Add support for handling solidity Structs in subgraph mappings. They will be seen in:
    1. emitted event params
    2. output of contract calls
    3. params decoded from `transaction_input` 

### Proposal

- Update ethabi to include support for decoding and representing Solidity structs
    - Create a new `Struct` type in `ethabi`
        - The types of the values in the struct are already supported, so it will be a wrapper type similar to `Array<>`
- Add `Struct` to `graph-ts`, representing it as an extension of `TypedMap` in `graph-ts` ultimately allowing it's key-values to be accessed from the event params with chained, dot notation in a mapping.
- Update ABI validation and codegen to handle `tuples` which map to Solidity `Structs`.

### Implementation

`ethabi`

- [ ]  support Solidity `Structs`
    - [ ]  add `Struct` type to ethabi
    - [ ]  update `ethabi::token::Tokenizer` to handle `Struct`
        - [ ]  new function `Tokenizer::tokenize_struct()` which is used in `Tokenizer::tokenize()`
    - [ ]  update `ethabi::token::Token` to include `Struct` variant
    - [ ]  update `ethabi::param_type::ParamType` to include `Struct` variant

`graph-ts`

- [ ]  Add `Struct` class
    - [ ]  add `Struct` class as extension of `TypedMap<K, V>`
    - [ ]  add `Struct` as variant in `EthereumValueKind`
    - [ ]  add `EthereumValue.toStruct()`

`graph-cli`

- [ ]  codegen: add support for generating types from `tuples` (map to `Structs` in Solidity)
    - [ ]  add `tuple/Struct` handling to `abi.generateTypes()`
    - [ ]  add `Struct` conversions between Ethereum values and Assemblyscript values (`codegen/conversions.js`)

### Compressed to Tasks

- [ ]  `ethabi`: Support Solidity `Structs`: add the `Struct` type, add `Tokenizer::tokenize_struct()`, and add corresponding `Struct` variants to `ParamType` and `Token`
- [ ]  `graph-cli`: Add `Struct` to codegen and validation (represented as tuple in the ABI)
- [ ]  `graph-ts`: Add a `Struct` class, and  implement conversions to and from `EthereumValue` using a new variant `EthereumValueKind::Struct`

**Comment by Jannis** [comment]
I've yet to review the above but quickly wanted to point to a contract that uses structs:

https://github.com/MolochVentures/moloch-monorepo/blob/master/packages/moloch/contracts/Moloch.sol#L79-L81

Here, the public state variables `members` and `proposalQueue` become view functions in the ABI that (should) return structs. Curiously enough, I don't see them returning structs:

https://github.com/MolochVentures/moloch-monorepo/blob/2f5b17496a7517eb833ac99b84e7b2402a2fc8e9/packages/moloch-subgraph/abis/Moloch.abi#L17-L48

Please check with @jamesyoung, he was asking for struct support recently and may be able to point you at where it was needed.

**Comment by Jannis** [comment]
@fordN: Does the ethabi decoder also have to be updated for structs? If not, then ignore me. If it does, then that would be another task.

**Comment by mrwillis** [comment]
I'm a big proponent of this feature. Would use it as soon as it comes out. Some things:

You guys could also use the ethers.js ABI decoder. I am actually not sure about the internals but I know the maintainer made his own. Maybe worth a look. I actually think web3@1.0 uses this under the hood as well.

https://docs.ethers.io/ethers.js/html/api-advanced.html

**Comment by Jannis** [comment]
@fordN Closing this as it is done. Please reopen if any of the tasks are still open.
