### ISSUE TITLE
Limit total number of entities to return

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#770]
Calculate the number of possible entities returned from a query (similar to GitHub's GraphQL explorer) and fail if the number exceeds a limit defined by an environment variable.

**Comment by leodasvacas** [comment]
This check should be done in the `graphql` crate. The best place to do this is probably in `fn execute_root_selection_set`, in `graphql/src/execution/execution.rs`. That function receives a [SelectionSet](https://docs.rs/graphql-parser/0.2.2/graphql_parser/query/struct.SelectionSet.html). Since we don't currently support fragments, that simplifies the logic, we can recursively dive into the selection set fields (which may also contain selection sets) and calculate the number of entities the query might return. The calculation should be done as described in the [github API docs](https://developer.github.com/v4/guides/resource-limitations/).

**Comment by nenadjaja** [comment]
Assigning it back to @leodasvacas since I got stuck with other stuff.. Sorry Leo. I'll be studying Rust on the side for sure, and will be able to help with future (smaller) tasks

**Comment by leodasvacas** [comment]
### Requirements

- Each query should have a maximum complexity, calculated based on the amount of entities returned, as described in the [github API docs](https://developer.github.com/v4/guides/resource-limitations/).
- If a query exceeds the complexity, it should not be executed and instead return an error.

### Proposed solution
- Check the complexity in `execute_root_selection_set`, before executing the query. Walk the AST selection set tree to calculate the complexity, using the `first` argument.
- Set the complexity limit as an env var, defaulting to no limit.

### Tasks

- [ ] Implement the solution in graph node.

**Comment by Jannis** [comment]
@leodasvacas A couple comments:

* Doing it in `execute_root_selection_set` feels ok for queries but for subscriptions, it would be better if we caught this at the time the subscription is set up and then reject the subscription from the start. So I'd prefer for this to be a standalone function that we run either in `GraphQlRunner` or in `execute_query` / `execute_subscription` before executing a query and/or subscription.

* About the first requirement: <q>amount of entities returned</q> is almost accurate. It's more <q>potential amount of entities returned<q>, which is roughly estimated using the `first` arguments + one-to-one relationships.
