### ISSUE TITLE
Block & transaction triggers

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#788]

**Comment by olibearo** [comment]
This is the task set imported from the Product board:

- Add a `find_first_blocks_with_transactions` method to the eth adapter
- Add a `find_first_blocks_with_triggers` method to the eth adapter and use it here: https://github.com/graphprotocol/graph-node/blob/c4f9e2fed8ef2e6f9e0c3076d20b019e898ed387/datasource/ethereum/src/block_stream.rs#L330. This method should interleave the results of `find_first_blocks_with_logs`, `find_first_blocks_with_transactions`, and be made aware of the subgraphs block handlers (with filters which will be satisfied using the `find_first_blocks_with_transactions`) to return a set of N (at most) blocks which the block stream will populate before yielding
- Add a `find_transactions_in_block`method to the eth_adapter to populate the blocks produced by `find_first_blocks_with_triggers` with transaction triggers. Since the trace filter method only accepts block numbers, this method should ensure that the block hash for the returned traces matches the block hash the caller expects
- Add an `EthereumBlockWithTriggers` struct which wraps `EthereumBlock` https://github.com/graphprotocol/graph-node/blob/c4f9e2fed8ef2e6f9e0c3076d20b019e898ed387/graph/src/components/ethereum/types.rs#L5 with a `triggers` property which is a vector of the enum `EthereumTrigger`. The block stream will yield this type
- Update the blockstream trait to emit `EthereumBlockWithTriggers`
- In processing each descendant blocks ptrs returned from `find_first_blocks_with_triggers`, the `block_stream_context` will pull down the full block and and relevant traces to populate the the new `triggers` property of the `EthereumBlockWithTriggers` struct
- Update the block stream processing in `SubgraphInstance` to handle Ethereum triggers and call block/transaction handlers
