### ISSUE TITLE
Split up entities table

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#793]

**Comment by lutter** [comment]
We want to break up the one big `entities` table into an `entities` table per subgraph. To that end, we'll create a new Postgres schema for each subgraph, and put the `entities` and `entity_history` table into that scheme. It should be possible to do that with minimal issues with Diesel, as we can select the subgraph-specific schema by setting Postgres' `search_path` before querying/modifying one of htese tables.

**Comment by Jannis** [comment]
I love the schema idea, because it's so unobtrusive. I have one question about the first task: Do we even need a mapping table if we use the subgraph deployment ID as the schema name (or suffix). E.g. `deployment_${id}` or `subgraph_${id}`?

**Comment by Jannis** [comment]
Another comment: I've marked #795 as a duplicate of this issue, but I think it needs to be incorporated into the plan. Splitting up existing tables with a migration is one thing, but the tables will also have to be created for new subgraphs going forward.

**Comment by lutter** [comment]
> I love the schema idea, because it's so unobtrusive. I have one question about the first task: Do we even need a mapping table if we use the subgraph deployment ID as the schema name (or suffix). E.g. `deployment_${id}` or `subgraph_${id}`?

There's a few reasons why I want a separate table for that:

* I'd want to use that table to version the schema for each subgraph, so that we do not need to migrate all subgraphs at once (I would stick a `version` column, and probably a `status` column to track status of migration for each subgraph into that table). To actually migrate into a split entities table, I am thinking of the following process (i.e., migrating from subgraph schema version 0 to 1):
  - initial migration only pulls out `subgraphs` subgraph
  - over time, we stop ingestion for individual subgraphs, and migrate their data out of the `entities` table (not quite clear what would trigger that, but I am thinking we have the ingestor for each subgraph check whether it needs migrating, and kick off the migration based on that only fewer than N otehr subgraphs are currently migrating)
  - when all subgraphs have been migrated, we can drop the entities table; not clear what should happen to unassigned subgraphs, as they would not be migrated with the scheme above
* I don't ever want to have to type stuff like `select count(*) from qma2wsszn3gsx2hdds47vx3vzudgdblebfjehuvp3j3zmv.entities` in psql :wink: 

> Another question: We also need to set `search_path` before _writing_ entities, correct, performing reversions etc., correct?

Yes, that's correct; though I am actually not that excited about the whole `search_path` thing since it will not show up in logs, and therefore make it much harder to follow which queries we are running. I am leaning towards using the dynamic table diesel crate, so that logs will actually show the fully qualified table name, like `select count(*) from sgd0.entities where entity='Subgraph'`

**Comment by lutter** [comment]
This work is done as of PR #950 and graph-node release v0.13.0
