### ISSUE TITLE
Time travel queries

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#813]
We currently only run queries as of the latest block. We will want a way to run queries as of a specified block. There are also use cases where people want to query information about how an entity has changed over time. That could be considered as part of this epic or broken out into a separate one.

**Comment by lutter** [comment]
Here is a writeup on how we intend to address time-travel queries. It's mostly about the internal plumbing, but might be useful in understanding in where we intend to go:

# Time-travel queries

## Goal

We want to make it possible to submit queries against the state of subgraph entities at a certain point in the past. Users should be able to indicate against which block a query should be run. The result of the query will only reflect the state of entities up to that block, and ignore any changes to entities that happened after that block.

## Approach

We can achieve this goal by storing all entities, including old versions, in one table, and tagging them with the range of block numbers for which each version is valid. An entity version that is tagged with a block range `[B1, B2)` is only valid for queries against blocks from `B1` to `B2-1`.

With this approach, creating an entity corresponds to inserting a new row into the `entities` table, deleting an entity corresponds to setting the upper bound of the latest entity version, and updating the entity corresponds to updating the upper bound of the old version and inserting a new version.

A nice benefit of this approach is that we do not modify the data for existing entities. The only attribute of an entity that can ever be modified is the range of blocks for which a specific entity version is valid.

## Schema

The following sets up an `entities` table that allows multiple entries for each entity (identified by `(subgraph, entity, id)`), but requires that the `block_range` for any two such entries is disjoint:

    CREATE EXTENSION IF NOT EXISTS btree_gist;
    
        CREATE TABLE entities (
           id VARCHAR NOT NULL,
           subgraph VARCHAR NOT NULL,
           entity VARCHAR NOT NULL,
           data jsonb NOT NULL,
           block_range int4range NOT NULL,
           EXCLUDE USING GIST (subgraph    WITH =,
                               entity      WITH =,
                               id          WITH =,
                               block_range WITH &&)
       );

For background on ranges in Postgres, see the [rangetypes](https://www.postgresql.org/docs/9.6/rangetypes.html) and [range operators](https://www.postgresql.org/docs/9.6/functions-range.html) chapters in the documentation.

## Operations

For all operations, we assume that we perform them for block number `B`; for most of them we only focus on how the `block_range` is used and manipulated. The values for omitted columns should be clear from context.

### Querying for a point-in-time

Any query that selects entities will have a condition added to it that requires that the `block_range` for the entity must include `B`:

    select .. from entities
        where ..
          and block_range @> $B

### Create entity

Creating an entity consist of writing an entry with a block range marking it valid from `B` to infinity:

    insert into entities(subgraph, entity, id, block_range, ...)
        values ($SUBGRAPH, $ENTITY, $ID, '[$B,]', ...);

### Delete entity

Deleting an entry consists of 'clamping' the block range of that entity to not be valid for blocks with numbers greater or equal to `B`:

    update entities
        set block_range = int4range(lower(block_range), $B, '[)')
        where subgraph = $SUBGRAPH and entity = $ENTITY and id = $ID
          and upper_inf(block_range) = 't';

### Update entity

Updating an entity consists of deletion of that entity followed by creation:

    update entities
        set block_range = int4range(lower(block_range), $B, '[)')
        where subgraph = $SUBGRAPH and entity = $ENTITY and id = $ID
          and upper_inf(block_range) = 't';
    
        insert into entities(block_range, ...)
        values ('[$B,]', ...);

### Rolling back

When we need to revert entity changes that happened for blocks with numbers higher than `B`, we delete all entities which would only be valid 'in the future', and then open the range of the one entity entry for which the range contains `B`, thereby marking it as the current version:

    delete entities
        where subgraph = $SUBGRAPH and entity = $ENTITY and id = $ID
          and lower(block_range) >= $B;
    
        update entities
        set block_range = int4range(lower(block_range), NULL, '[)')
        where subgraph = $SUBGRAPH and entity = $ENTITY and id = $ID
          and block_range @> $B;

### Confirmations

A confirmation for a piece of data indicates how long that piece of data has not changed, the longer the more certain we can be that it will not be affected by a block reorganization.

The `block_range` for the different versions of an entity that we store in the `entities` table are disjoint, and therefore induce an ordering of these versions. We can list them with a query like

    select * from entities
        where subgraph = $SUBGRAPH and entity = $ENTITY and id = $ID
        order by lower(block_range) desc

The `block_range` for the first entry in that order tells us how long it has been since this entity has been changed - the entity has been unchanged since `lower(block_range)` for that entity. It can actually be identified more easily as the single version of the entity whose `block_range` does
not have an upper bound.

We can also use this ordering to determine how long a specific attribute of an entity has not been changed by looking for the newest version of the entity that has a value that differs from the current value. The details of that query are TBD.

## Notes

- It is important to note that the block number does not uniquely identify a block, only the block hash does. But within our database, at any given moment in time, we do have a notion of the block hash that a given block number corresponds to for a given subgraph, even if we do not seem to track the `(subgraph, block_nr) -> block_hash` mapping explicitly. It might become necessary to introduce a table for this.
- It's not entirely clear to me what the best way to expose this functionality in the API would be. It might be best to make the block number (or hash?) for which a query should be run a global parameter for the query (can that be done with a request parameter?)
- What is the right range for entities in the special `subgraphs` subgraph? Do we treat them just like we do 'normal' entities?
- Migrating from our current schema to this new schema will be a bit of a headache since the migration will take quite a bit of time, and we need to make sure that we catch all changes to `entities` and `entity_history` while the migration is running. The migration will need to use the information in `entity_history` to insert entries into the `entities` table with the right block ranges. Once the migration is done, we can drop `entity_history`. Possible strategies, in order of implementation complexity, are
    - Take complete downtime for the migration (i.e., turn off all indexing nodes)
    - Turn off all other writes to the database while the migration is running; turning off block ingestion for a bit does not seem like a big deal, but since subgraph metadata is also stored in the `entities` table, we'd also need to turn off any changes to subgraphs, like subgraph deployment.
    - Iteratively migrate `entity_history` into `entities`in parallel with ongoing write activity. That should get us to a situation where we have very little migration activity left to do (only what was written concurrently with the last iteration of migrating) We can then take exclusive table locks on these two tables (temporarily blocking all other writes) to migrate that little bit. Until we are fully migrated, the `graph-node` code would need to write entity changes following both approaches to maintaining history, the old and the new one, but continue to read according to the old approach until the migration is complete.
