### ISSUE TITLE
Block ingestor gets stuck with short chains (e.g. Ganache)

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#844]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When running Graph Node against a short Ethereum chain, such as Ganache with only the transactions from the [example subgraph](https://github.com/graphprotocol/example-subgraph), the block ingestor gets stuck and never catches up with the chain. Subgraphs that are deployed against the node never start indexing.

Excerpt of the log of running `docker-compose up` with `GRAPH_LOG: debug`.
```
graph-node_1  | component: BlockIngestor
graph-node_1  |  Mar 28 16:55:25.051 DEBG Trying again after eth_getBlockByHash RPC call failed (attempt #18)
graph-node_1  |  Mar 28 16:55:52.653 DEBG Trying again after eth_getBlockByHash RPC call failed (attempt #19)
graph-node_1  |  Mar 28 16:55:57.298 DEBG Trying again after eth_getBlockByHash RPC call failed (attempt #20)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Clone graph-node
2. Start a fresh instance of Ganache (e.g. with `ganache-cli`)
3. Add `GRAPH_LOG: debug` to the `graph-node > environment` section in `docker/docker-compose.yml` in graph-node
4. Run `cd docker/ && docker-compose up` in graph-node
5. Run `graph init --from-example foo/test-subgraph` followed by `cd test-subgraph && yarn create-local && yarn-deploy-local`

The Docker image should log the above `eth_getBlockByHash` retry messages and the subgraph should log `Start subgraph` but process no events after that.

**What is the expected behavior?**

The block ingestor succeeds ingestion blocks and the subgraph starts indexing properly.

**Comment by Jannis** [comment]
A temporary workaround is to add
```
      ETHEREUM_REORG_THRESHOLD: 1
      ETHEREUM_ANCESTOR_COUNT: 1
```
to the `graph-node > environment` section in `docker-compose.yml`.

**Comment by Jannis** [comment]
`git bisect start master 6d1899a4848b4fb6c453200dedf3dac66411195a` points at one (or more) of the following commits to be the culprit:
```
6ac9934c5aacd295587ff1a477ab5aec7f0bfad0
138716d7d737f063a99b79486e6b4fe90b2d3aaf
53b2968d92f4745d42c6b0888b21b6757b807c8e
48383c9a8b76299e006ab4b116c4215a99135630
c9dbb2b9090b1ec12fcbaf79fc9ed805feb956e9
40d87a5dd7ac5d76d84657513694c91a7648c5a0
```

**Comment by Jannis** [comment]
I took a closer look at the commit. I'm not quite sure what is going on yet but this is what I'm observing so far:

* There is a change from `>` to `>=` in the commit that I'm not sure is correct. See this line: https://github.com/graphprotocol/graph-node/commit/48383c9a8b76299e006ab4b116c4215a99135630?diff=unified#diff-0f3b42a7fc8ab3cd4626fc039ef4fd13R51. Changing that to `>` gets rid of the
  ```
  Trying again after eth_getBlockByHash RPC call failed (attempt #20)
  ```
  logs but doesn't make things work yet.

* The loop that ingests missing blocks keeps looping infinitely, with `missing_block_hashes` being identical in every iteration: https://github.com/graphprotocol/graph-node/blob/14504c61be3f7304d9ae64080b027e0483fe4fd4/datasource/ethereum/src/block_ingestor.rs#L149-L162

**Comment by lutter** [comment]
Does the chain have fewer than `ancestor_count` blocks?

What that query does is build a list `(hash, parent_hash)` in the form `(h1, h2) (h2, h3) (h3, h4)` etc. and checks that for each `parent_hash` in those tuples, there's also one where that hash value appears in the first (`hash`) position. In other words, it checks that for `ancestor_count` blocks from the new head we have a complete chain in the DB. That chaining of `(hash, parent_hash)` will of course fail for the last (oldest ancestor) we select, since that block's parent will not be in the list we check. That's why `head.last` gets set to true for that last tuple, and we ignore it in our chain checking.

If the chain is shorter than `ancestor_count` blocks, this will fail because `head.last` will be false for all rows, and we'll always report the oldest ancestor as missing a parent. One way to fix this is to also query the `genesis_block_hash` from `ethereum_networks` on line 17.

We can then modify the query on lines 45-56 to
```
WITH head AS
        (SELECT hash,
                parent_hash,
                (number = (new_head_number - ancestor_count) or hash = genesis_block_hash) as last
           FROM ethereum_blocks
          WHERE network_name = net_name
            AND number >= GREATEST(new_head_number - ancestor_count, 0))
    SELECT array_agg(h1.parent_hash)
      INTO STRICT missing_parents
      FROM head h1
     WHERE not h1.last
           AND NOT EXISTS (SELECT 1 FROM head h2 WHERE h1.parent_hash = h2.hash);
```

I haven't tried this, but that's what I think is going on based on your investigation. (Great detective work btw)

The `>=` is there so that we have `ancestor_count` blocks with parents in the `head` query. If you change it to `>`, you'd only be checking `ancestor_count - 1` blocks.

**Comment by Jannis** [comment]
> Does the chain have fewer than ancestor_count blocks?

Yeah, default ancestor count is 50 but if you use the [example subgraph](https://github.com/graphprotocol/example-subgraph/) and run Ganache + `truffle compile && truffle migrate` that'll end up creating just 8 blocks on Ganache.

**Comment by Jannis** [comment]
Let's merge this now so we can get it out to people.
