### ISSUE TITLE
Postgres password shouldn't be printed to the logs

### ISSUE THREAD

**Issue by iameli** [graphprotocol/graph-node#849]
Hi! I love this project.

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I set up a Docker node with `graphprotocol/graph-node:latest`, using the environment variables to provide my postgres username and password. That password that I provided is being logged twice — first by `bash` when the Docker image boots up:

```
+ graph-node --postgres-url postgresql://postgres:[redacted password here]@127.0.0.1:5432/subgraph --ethereum-rpc mainnet:http://ethereum-rpc.default.svc.cluster.local --ipfs localhost:8080
```

And again by subgraph itself when it starts the connection:

```
Apr 01 21:34:54.671 INFO Connecting to Postgres, url: postgresql://postgres:[redacted password here]@127.0.0.1:5432/subgraph
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

The application log happens on every run of the software. The Docker log happens on every run of the software in the Docker container that doesn't include a custom command.

**What is the expected behavior?**

No password logging to stdout or stderr please! Security best practices and all that.

**Comment by Jannis** [comment]
Fully agree, thanks for the report!

**Comment by adzialocha** [comment]
Is this really resolved? The password does not show up inside graph logs anymore, but since its still written plaintext as a command line argument its visible in `htop`, and docker logs. @iameli mentions `bash` as well.

Maybe adding a `.env("POSTGRES_URL")` etc. option to the Clap configuration in `main.rs` can already solve this problem? https://github.com/graphprotocol/graph-node/blob/master/node/src/main.rs#L114-L120
