### ISSUE TITLE
Could too many Postgres notifications lead to dropped store events?

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-node#936]

**Comment by lutter** [comment]
According to [the docs](https://www.postgresql.org/docs/9.6/sql-notify.html), this should not be an issue:

* the notification queue has room for 8GB of payload, and with the limitiation of 8k/message, that's enough for 1M queued messages
* if `notify` fails because the queue is full, the transaction calling `notify` will fail to commit; we will therefore not silently drop notifications
* once the queue is half full, [Postgres logs warnings](https://postgrespro.com/list/id/56C732DE.5090509@aklaver.com). I could not find any warning messages in our logs

**Comment by lutter** [comment]
Closing this since there is no further action needed.
